### ISSUE TITLE
Logging without batching

### ISSUE THREAD

**Issue by qodex2** [FantasticFiasco/serilog-sinks-http#112]
I'd like to be able to send http events without batching in an array.  I set batchPostingLimit: 1, but that just gave me an array of 1 event.  I created my own IBatchFormatter by cloning DefaultBatchFormatter and removing  the "events" array.  LogEvent doesn't appear to override ToString, and I can't find an extension method, so output.Write(logEvent) just writes the name of the class into the stream.

What can I do to resolve this?

**Comment by FantasticFiasco** [comment]
I'm just writing from the top of my head, but I think the following batch formatter should suffice given you've set a batch posting limit of 1.

```csharp
class SingleEventBatchFormatter : IBatchFormatter
{
    public void Format(IEnumerable<LogEvent> logEvents, ITextFormatter formatter, TextWriter output)
    {
        formatter.Format(logEvents.Single(), output);
    }

    public void Format(IEnumerable<string> logEvents, TextWriter output)
    {
        output.Write(logEvents.Single());
    }
}
```

You would get them as a single JSON object on the receiving side. Please try it out and get back to me.

**Comment by qodex2** [comment]
That definitely removed the array, thanks!

I have one more question if you don't mind me asking, and if you're the right person to ask.  In this HTTP body which is what SingleEventBatchFormatter produced:

```
{
   "Timestamp": "2020-05-14T21:20:28.7858526-04:00",
   "Level": "Verbose",
   "MessageTemplate": "This is a Verbose message for Acme Widgets",
   "Properties": {
      "MachineName": "GSG-F1293",
      "EnvironmentUserName": "GSG\\tbomgard",
      "type": "diag"
   }
}
```
Is there any way to move "type": "diag" (added with an enricher) to the outer level, so it appears along with "Timestamp" and "Level"?

Thank you again!

**Comment by FantasticFiasco** [comment]
As we have `IBatchFormatter` for formatting a batch of log events, we have `ITextFormatter` for formatting a single event. The default event formatter used is [`NormalRenderedTextFormatter`](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/src/Serilog.Sinks.Http/Sinks/Http/TextFormatters/NormalRenderedTextFormatter.cs) and the bulk of the implementation is found [here](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/src/Serilog.Sinks.Http/Sinks/Http/TextFormatters/NormalTextFormatter.cs).

Copy the file, rename it and render your special property wherever you'd like.

**Comment by qodex2** [comment]
Thank you!
