### ISSUE TITLE
Failover Support

### ISSUE THREAD

**Issue by rGunti** [FantasticFiasco/serilog-sinks-http#134]
**Is your feature request related to a problem? Please describe.**
Provided you ship logs through HTTP to an endpoint and it goes down, currently the logs will be held on disk until the endpoint is reachable again. However some libraries support the use of multiple endpoints where, depending on the use-case, you can either ship the data in a balanced way to distribute load, or via a failover mechanism whereby a list of targets is provided and the app is then sending it to the next available endpoint. If the submission fails, the next one will be picked.

**Describe the solution you'd like**
In the configuration, the user can provide multiple endpoints. JSON config sample:
```
{
/* ... */
            {
              "Name": "DurableHttpUsingTimeRolledBuffers",
              "Args": {
                "requestUri": ["http://log1.example.com/", "http://log2.example.com/", "http://log3.example.com/"]
              }
            }
/* ... */
}
```
The Sink delivers the data to either always the first or a random endpoint in the list. If data could not be sent (timeout, server error, etc.), a new host will be picked and the failing host will be blacklisted for a certain amount of time (could also be optionally configured).

**Describe alternatives you've considered**
An alternative could be a sink that wraps multiple Http sinks where only one is picked to submit data unless it is not available.

**Additional context**
-

**Comment by FantasticFiasco** [comment]
Hi @rGunti!

I would place the concept of failover in the domain of availability, and availability is often solved at the network level. I would propose that the problem was solved by e.g. a reverse proxy or cloud services like AWS API Gateway, not by the data producer.

I like that you're thinking about failover, but I don't think the solution to it should be implemented on the data producing side. Does that seem reasonable to you?

**Comment by rGunti** [comment]
Hey @FantasticFiasco 

I agree with you fully, however that is not always achievable, especially if you can't control the target. And while one could just log to multiple targets simultaneously, that would just be a waste of traffic.

That said, if you feel like this should not be part of this sink, that is also totally fine as one can always extend them on their own. I thought it might be a nice feature to have since I know this from other similar log outputs from other libraries.

**Comment by FantasticFiasco** [comment]
It's definitely an interesting feature to support, but I'm afraid that the amount of work it would take, including the complexity of testing failover, somewhat exceeds its value.

**Comment by rGunti** [comment]
Closing the issue since this won't be implemented.
