### ISSUE TITLE
The type 'IConfiguration' exists in both Microsoft.Extensions.Configuration.Abstractions and Serilog.Sinks.Http

### ISSUE THREAD

**Issue by brian-pickens-web** [FantasticFiasco/serilog-sinks-http#135]
**Describe the bug**
Serilog.Sinks.Http contains `Microsoft.Extensions.Configuration.Abstractions.IConfiguration` type and conflicts with the same type inside Microsoft's configuration package. Why not put a package dependency on `Microsoft.Extensions.Configuration.Abstractions` instead?

Is there currently a recommened way to deal with this?

```
Error	CS0433	The type 'IConfiguration' exists in both 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Serilog.Sinks.Http, Version=7.0.1.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'	SomeProject	C:\...\SomeFile.cs	18	Active
```

Edit:
I dug into the source for this type and noticed that it is wrapped with compiler flags to include it into non netcore 2.0 targeted applications. Is there a reason for this? That means that I can't use this sink with any other framework along with Microsoft's configuration library?

**Comment by brian-pickens-web** [comment]
FYI - My short term solution to fixing this is downgrading to v6, before the type was added.

**Comment by FantasticFiasco** [comment]
Maybe I've misconfigured the compiler flag. Which .NET version are you using?

**Comment by FantasticFiasco** [comment]
And which version of [Microsoft.Extensions.Configuration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/3.1.8) are you referencing?

**Comment by brian-pickens-web** [comment]
3.1.8

**Comment by FantasticFiasco** [comment]
Yeah I think you are correct. I'll have to fix this issue, but haven't got the time tonight. I'll start working on it during the weekend, are you able to use the old version until a fix has been created?

**Comment by MCCshreyas** [comment]
@FantasticFiasco As the type will be available for all .NET Standards version, do we need to remove that type from the library?

**Comment by FantasticFiasco** [comment]
Yes, that will be the first thing I investigate. I'm happy to do it, but if any of you are participating in Hackoctober you are free to open up a PR and count is as a part of your monthly goal. Just make sure I've got permissions to push to your fork.

**Comment by MCCshreyas** [comment]
@FantasticFiasco yeah, I just forked the repo, and will try to fix this issue, and will create PR with a solution! 😀

**Comment by FantasticFiasco** [comment]
I just wanted to wrap my head around this thing. My intention is to keep the same API for all supported versions, and [shim](https://en.wikipedia.org/wiki/Shim_(computing)) `IConfiguration` where it isn't supported. But I think I got it wrong, let me explain why.

Let's start with the .NET version we build for.

- `net45`
- `net461`
- `netstandard1.3`
- `netstandard2.0`

Now let's look at the versions [Microsoft.Extensions.Configuration v3.1.8](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/3.1.8) is built for.

- `netcoreapp3.1`
- `netstandard2.0`

According to [.NET implementation support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), this is the .NET implementation support.

| .NET Standard | 1.3 | 2 |
| --- | --- | --- | 
| .NET Framework | 4.6 | 4.6.1 |

That ought to mean that the following versions we build for is supported by `netstandard2.0`.

- [ ] `net45`
- [x] `net461`
- [x] `netstandard1.3`
- [x] `netstandard2.0`

Which lets me believe that the only version we need to shim support for `IConfiguration` is `net45`.

Can any of you please verify my reasoning?

**Comment by aleksaradz** [comment]
@FantasticFiasco Your reasoning looks correct to me... Projects that target .NET 4.6.1 can consume .NET Standard 2.0 libraries and can consume `IConfiguration` directly from [Microsoft.Extensions.Configuration v3.1.8](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/3.1.8) because it has a target to .NET Standard 2.0. I also tested [Microsoft.Extensions.Configuration v3.1.9](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/3.1.9) and the same is true.

I can help with the pullrequest if you want

**Comment by FantasticFiasco** [comment]
I would love it, if you are willing. Please let me know if I can help in any way.

**Comment by aleksaradz** [comment]
@FantasticFiasco I just open pullrequest #139

**Comment by FantasticFiasco** [comment]
@aleksaradz, the changes where perfect!
@brian-pickens-web, I'll continue with creating a release.

**Comment by FantasticFiasco** [comment]
@brian-pickens-web [v7.1.0](https://www.nuget.org/packages/Serilog.Sinks.Http/7.1.0) is now live on nuget.org. Would you be able to verify that it fixes this issue?
