### ISSUE TITLE
dependency on deprecated Serilog.Sinks.RollingFile

### ISSUE THREAD

**Issue by tipasergio** [FantasticFiasco/serilog-sinks-http#162]
Still have dependency

**Comment by FantasticFiasco** [comment]
Hi @tipasergio!

You are correct. [Serilog.Sinks.RollingFile](https://github.com/serilog/serilog-sinks-rollingfile) is an archived project, but the last time I checked at [Serilog.Sinks.File](https://github.com/serilog/serilog-sinks-file) it didn't match the behaviour of the time rolled durable sink we have in this repository. I'll add it to my todo list to take another look.

Are there any other information regarding Serilog.Sinks.RollingFile that would increase the priority of this issue? Has the package been flagged in one of your security vulnerability scans?

**Comment by FantasticFiasco** [comment]
@tipasergio, the dependency has now been removed in [v8.0.0-beta.5](https://www.nuget.org/packages/Serilog.Sinks.Http/8.0.0-beta.5). Thanks for bringing this to my attention!
