### ISSUE TITLE
New Feature/Enhancement Request: Support Gzip Compressed logs over HTTP

### ISSUE THREAD

**Issue by vaibhavepatel** [FantasticFiasco/serilog-sinks-http#166]
**Is your feature request related to a problem? Please describe.**

We are using the Http sink in some of our applications to write to a Fluentd agent. One application creates logs that are larger than the conventional logs due certain requirements. Most cases, the logs are larger than 5MB and sometimes even as large as 10MB. In another application where we use this sink, most logs are less than ~500 KB, but it produces thousands of logs per second. To support the large size and high number of logs, I am using a custom array batch formatter with a size of 16MB.  Now I want to conserve network bandwidth and reduce the latency by using Gzip compression on the logs and sending it over http. 

This would be beneficial for some people that want to use the http sink wanting to conserve bandwidth, reduce latency and decrease the number of http requests for shipping the logs. In the case of applications running in the cloud, this would reduce ingress/egress costs (Fluentd and Elasticsearch both support compressed logs over http. Provided links in the additional context section)

Pros:
- Reduce network bandwidth for large logs
- Reduce http request latency for large payloads
- Each log will take up less storage on the FS
- More logs can sent over one http request using the same batch size
- Fluentd and Elasticsearch both support compressed logs over http
- Reduce ingress/egress data transfer costs when running within cloud ([Costs for AWS](https://www.nops.io/blog/aws-data-transfer-cost-operation/))

Cons:
- Application performance (CPU/Memory) may be impacted when compressing logs. Would need to do a comparison to see the impact as it would vary based on size and throughput.
- The backend application needs to support Gzip compressed http requests.

**Describe the solution you'd like**

I've done a little investigation into integrating it with 'DurableHttpUsingFileSizeRolledBuffers' and here are my findings. I went through the sink code and found that you are internally using the File sink for the file buffer. The File sink has a [FileLifeCycle Extension](https://github.com/serilog/serilog-sinks-file#extensibility) that supports [Gzip hook](https://github.com/cocowalla/serilog-sinks-file-gzip) which can be leveraged to write Gzip compressed logs into the file (I was able to get this working after making changes locally and can share these changes, if you'd like to see).

Next, we would need to implement a Http Client that supports Gzip compressed request payloads. This would require making changes to the existing http client or creating a new http client to support this. A new formatter would also need to be created to make sure the batch is created in gzip format and appends gzip logs. 

I did test to make sure that logs can be sent compressed over http and is received properly by the end client before requesting this feature. In the code shared below, I am taking a string serialized into json, converting it into byte stream, compressing it and sending it over http. 

Is it possible that this can be integrated into the Http Sink? If so, I can contribute by working on this feature, and I would also be able to test it as this is something we would like to use.
 
**Describe alternatives you've considered**
I haven't considered any other alternatives other than sending the logs uncompressed over http. 

**Additional context**

Http compression support:
- [Fluentd](https://docs.fluentd.org/input/http#use-compression-to-reduce-bandwidth-overhead)
- [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/modules-http.html)
- [AWS Elasticsearch](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/gzip.html)

The sample code I used to create compressed payload and sent over http to Fluentd instance:
```
        private const string jsonValue1 = "{\"LogLevel\":\"Information\",\"Message\":\"Test1\",\"RequestId\":\"06c1b946-1474-4e63-bf49-944cf0e3541d\",\"LogTime\":\"02/12/2021 17:54:31.193324+00:00\"}";
        private const string jsonValue2 = "{\"LogLevel\":\"Information\",\"Message\":\"Test2\",\"RequestId\":\"1a810f65-a289-4e1c-873d-7dcd9078db5f\",\"LogTime\":\"02/13/2021 18:54:31.193324+00:00\"}";

        static void Main(string[] args)
        {
            // Create byte stream 
            var buffer = ConvertToBytes($"[ {jsonValue1}, {jsonValue2} ]");
            using var input = new MemoryStream(buffer);

            // Convert byte stream into Gzip Stream
            using var output = new MemoryStream();
            using (var gzipStream = new GZipStream(output, CompressionLevel.Optimal))
            {
                input.CopyTo(gzipStream);
            }

            // Create the Http Content stream w/headers
            using var contentStream = new MemoryStream(output.ToArray());
            var content = new StreamContent(contentStream);
            content.Headers.Add("Content-Type", "application/x-www-form-urlencoded");
            content.Headers.Add("Content-Encoding", "gzip");

            // Http post method
            using var client = new HttpClient();
            var response = client.PostAsync(content: content, requestUri: requestUri).Result;

            Console.WriteLine(response.IsSuccessStatusCode);
        }

        private static byte[] ConvertToBytes(string value) => Encoding.UTF8.GetBytes(value);
```

**Comment by FantasticFiasco** [comment]
Gzip looks interesting, but I would like to read up on in more, and finalize #116 before continuing with this. I think Gzip can be supported in a multitude of ways, and if we go ahead with this kind of highly integrated support I would love all help you can give me.

But I would also like to investigate the more easily, but perhaps less valuable, support where one only has to rewrite the HTTP client to supporting Gzip. I know we render some of the sink parameters useless if we go this route, but I wouldn't want to disregard an option before trying it out.

**Comment by vaibhavepatel** [comment]
Sure, I completely understand and you're right, there are multiple ways to support it. And modifying the Http Client to support Gzip would be great and would be extremely beneficial for my use case. 

Let me know when you've had a chance to read up on this and determined if we can move forward with it. If I have time, I'll try and take a look to see what changes can be made to the HttpClient using streams.

Also, I'm not sure where this case would be useful, but I think adding Brotli compression along with Gzip might also prove to be beneficial.

**Comment by FantasticFiasco** [comment]
I agree, if we go ahead with Gzip we should also look at Brotli.

But before we do anything, I would like to thank you for the time and effort you've spent analyzing the issue. It's much appreciated! ❤️

**Comment by vaibhavepatel** [comment]
Glad to be of help! 

Also, I forked the repo and made changes to the HttpLogShipper to support gzip/compression. Seems that there are a few other classes that would also need to be updated to support this. I should have these changes checked in later today/tomorrow. I'll update this post with a link to the changes. 

Once you've had a chance to investigate and determine if this is feature that can be supported, then I can submit a pull request if my approach looks good (probably might require some refactoring though). I'd also appreciate if this could be prioritized as this is something that we would like to use given that there are no other priorities.

**Comment by FantasticFiasco** [comment]
I can't promise anything. Not that the PR you are working on will be merged, nor that this can come before #116. Whether compression is supported in the buffer files or by having to write a custom HTTP client is still not analysed, nor determined.

The size of your log events is really something, and I don't mean that in a positive way. Having individual log events with > MB in size makes me question whether they actually are log events. Are they, or are they documents you pass on to other parts of the application?

**Comment by FantasticFiasco** [comment]
#116 has been merged to master and I'm ramping up to take on this issue.

I think we should start off by defining a target environment. I'm not keen on supporting Elasticsearch since there already exists another sink [for that](https://github.com/serilog/serilog-sinks-elasticsearch), but since you're already familiar with Fluentd maybe we should aim to support that one instead? Would you be able to validate the Gzip functionality in your environment, and deem whether enabling Gzip improved your situation?

**Comment by vaibhavepatel** [comment]
Hey @FantasticFiasco, I appreciate your efforts in investigating into the issues and completing #116. I'll probably upgrade to the new version later (hopefully by next week) and let you know if I find any issues.

Also, I haven't really had a chance to continue forward on this enhancement in the past week and I likely won't get a chance at least until next week. 

Yes, I agree, I am not looking to support Elasticsearch and was looking to support Gzip functionality by pushing logs over http into Fluentd. Regarding the test, did you want to conduct the test using the Http Sink with Gzip changes? If this is the case, then can you give me about ~2 weeks to get back to you on this?

**Comment by FantasticFiasco** [comment]
Yes, this sink with Gzip support in your environment, to validate that the changes improve your situation.

I'll start with this and understand that you won't be able to join me at this point in time. But if I may ask you one thing before I start, would you be able to share how you configure Fluentd to accept Gzip:ed payloads? I would like to setup an environment similar to yours to get a feel for what we're building for.

**Comment by FantasticFiasco** [comment]
Maybe Fluentd doesn't require any configuration as it seems to [support Gzip out of the box](https://docs.fluentd.org/input/http#use-compression-to-reduce-bandwidth-overhead)?

**Comment by vaibhavepatel** [comment]
Okay, got it, I can do that. 

Fluentd supports it out of the box in the http source and here is how the documentation on how to test it with fluentd [here](https://docs.fluentd.org/input/http#use-compression-to-reduce-bandwidth-overhead).

Below is the source configuration on my Fluentd. It requires the [fluent-plugin-multi-format-parser](https://github.com/repeatedly/fluent-plugin-multi-format-parser) plugin because I wanted to see any instances that a json log might have been received but not parsed.
```
<source>
  @type http
  @id in_http

  port 9880
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
  <parse>
    @type multi_format
    <pattern>
      format json
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
</source>
```

**Comment by vaibhavepatel** [comment]
Thanks for you patience, @FantasticFiasco. I implemented the changes and checked it into the [repo](https://github.com/vaibhavepatel/serilog-sinks-http). I tested the changes and it seems to be working well! However, the Unit Tests are still pending and will work on updating those this week. Although, I'd prefer if you took a look at the changes before I worked on the Unit Tests. 

Is there any specific type of test you would like me to run with the changes? I can work on executing tests under those conditions.

One thing to note: I tried to change the GZIP compression prior to the formatter but it didn't work out too well. It required lots of changes and also changes in all the formatters. This didn't seem like the best approach as it introduced too many changes. I tried a few different ways to refactor the GZIP compression but wasn't able to and found this worked the best.

**Comment by FantasticFiasco** [comment]
It's me that should thank you! You've invested a lot of time and energy in this, and I agree that we should take a step back and evaluate the situation before we go ahead and update the tests.

I've played around quite a bit with Gzip compression in [serilog-sinks-http-diagnostics](https://github.com/FantasticFiasco/serilog-sinks-http-diagnostics). I copied your code into a rudimentary implementation of the `IHttpClient` (you can find it [here](https://github.com/FantasticFiasco/serilog-sinks-http-diagnostics/blob/feat/gzip/src/app/HttpClients/GzipHttpClient.cs)). I was really astonished with the level of compression you get from Gzip. I've seen compression ratio of anywhere between 3x-10x depending on the repetitiveness of the log events, and that will be really good if you find yourself in an environment where you saturate the network. Based on these findings, I can assure you that this sink will get support for Gzip, one way or another.

There are some things I would like to finish up in *serilog-sinks-http-diagnostics* before I move my focus to this repo. I think we are better off extending this sink with a new HTTP client tailored toward Gzip. Basically what you've done already in your fork but moving it further down the pipeline into the HTTP client. Because as I understand your last part before the *EDIT*, there aren't any changes to how log events are persisted on disk? The log events are buffered as is, they are not buffered in a Gzip:ed state? If this is true, I'm really confident that we will sort this issue in the upcoming week.

Again, thank you for the time you've invested in this. If you open up a PR we can work together on this, and you can squash all commits in the end and get credit for the new feature.

**Comment by vaibhavepatel** [comment]
It's a team effort, but thanks! 😄 

Awesome! Glad to hear that gzip will be supported. Yeah, Gzip is great and I think it would be very beneficial in reducing network latency and bandwidth. 

Good idea on creating a separate HTTP Client. However, maybe instead of creating a new client altogether maybe we can create a new method on the existing client? That way we can parameterize gzip and the level of compression through the config?

Sounds good. I'll get a PR, hopefully, by tomorrow or day after with the changes I've done and we can work on refactoring or any updates.

**Comment by FantasticFiasco** [comment]
We'll make sure that the solution we chose is supporting both code and app config configuration. I'm on board with that.

Looking forward to the PR. We will do changes to the code, so don't make any changes the upcoming days that we perhaps might have to revert later on.

**Comment by vaibhavepatel** [comment]
Agreed. I have created a pull request based on the changes I did in the forked repo. Look forward to working on these changes with you over the next few days.

**Comment by FantasticFiasco** [comment]
[v8.0.0-beta.3](https://www.nuget.org/packages/Serilog.Sinks.Http/8.0.0-beta.3) is now available on nuget.org. Please try it out and get back to me with feedback.

Thanks for the collaboration!
