### ISSUE TITLE
Do not use .json extension for buffer files because there files are not actually valid json files

### ISSUE THREAD

**Issue by amityagov** [FantasticFiasco/serilog-sinks-http#169]
**Is your feature request related to a problem? Please describe.**
*.json based buffer files are not valid json files actually.
Rider IDE tries to parse these files and hangs for quite some time.

**Describe the solution you'd like**
Please, add ability to specify buffer file extension.

**Comment by FantasticFiasco** [comment]
You are correct, the buffer files are not valid JSON, but they are also considered to be an implementation detail and not a part of the API. Changing the file extension would be a breaking change. I'm not sure the performance of Rider can motivate a breaking change.

**Comment by amityagov** [comment]
Okay, maybe you can provide the way to change default behavior? Currently, it is not possible to change file extension for `DurableHttpUsingFileSizeRolledBuffers`, because it only has `bufferBaseFileName` parameter. However DurableHttpUsingTimeRolledBuffers has `bufferPathFormat` which allow developer to change file extension.

**Comment by FantasticFiasco** [comment]
We'll see what we can do. There are a lot of work planned ahead for this sink, let's see where this fits.

**Comment by rGunti** [comment]
@amityagov If it is still relevant for you: You can configure Rider to ignore the Buffer files so they don't chew away those CPU cycles.
Go to the Rider Settings > "Editor" > "Inspection Settings" > "Elements to Skip" and add the following file mask:
`Buffer-*.json`

![image](https://user-images.githubusercontent.com/5184813/113878521-f4fe9100-97b9-11eb-9453-e72e86ee9b7c.png)

**Comment by amityagov** [comment]
@rGunti Hello, it helped, thanks.
