### ISSUE TITLE
Round Robin based loadbalancing support

### ISSUE THREAD

**Issue by pankaj-k** [FantasticFiasco/serilog-sinks-http#177]
It will be nice if we could provide a comma or colon seperated url's in the requestUri. If the sink can do a round robin based load balancing between the two URI's that will be awesome. If it is already possible then please let me know. 

```
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Http" ],
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        "Name": "Http",
        "Args": {
          "requestUri": "http://serverone:9900;http://servertwo:9901"
          "loadBalance" : "true"
        }
      }
    ]
  }
}
```

The Elasticsearch Sink does [that](https://github.com/serilog/serilog-sinks-elasticsearch/issues/73) to some extent. 
Quoting what the person said:
That is correct. The ES sink uses the connection pool functionality. So normally you pass in a couple of endpoints and the client is clever enough to check health and connect to the available one.

**Comment by FantasticFiasco** [comment]
Hi!

This falls into the same ballpark as #134 and #157. It's a network problem that easily can be solved at the network level. There already exists solutions for this, and because of that I'm closing this issue.
