### ISSUE TITLE
Using serilog timestamp with custom timezone

### ISSUE THREAD

**Issue by solar-core** [FantasticFiasco/serilog-sinks-http#187]
Hello! How can i use custom timezone, not my local one, in timestamp field? Do i need to write a custom TextFormatter?

**Comment by FantasticFiasco** [comment]
The timestamp [is normally set by Serilog](https://github.com/serilog/serilog/blob/e9c90942b4c48ee821dbbac37d5fdb6e9c7134aa/src/Serilog/Core/Logger.cs#L371) when the log event is written. However, if you only use the method `ILogger.Write(LogEvent logEvent))` you can create the log event yourself with a timestamp that suits your requirements.

The other alternative is, as you propose, to adjust the timestamp before the event is sent, using an implementation of `ITextFormatter`.

**Comment by solar-core** [comment]
Thank you for suggestion, i understand that better now. I will choise the best option for me then.
