### ISSUE TITLE
HTTP streams begins with BOM

### ISSUE THREAD

**Issue by KalininAndreyVictorovich** [FantasticFiasco/serilog-sinks-http#188]
**Describe the bug**
HTTP streams sent by the sink begins with BOM. Some servers (at least ASP.NET core 2.1) fail to deserialize JSON begining with BOM. And it is violation of rfc8259.
This is a regression since v8.0.0-beta.3.

**To Reproduce**
1. Update Sample server https://github.com/FantasticFiasco/serilog-sinks-http-sample-dotnet-core to .net core 2.1
2. Update nuget package Serilog.Sinks.Http in Sample producer to version 8.0.0-beta.3
3. Run Sample producer
4. See errors in Sample server

**Expected behavior**
No errors even on  ASP.NET core 2.1 servers.

**Comment by FantasticFiasco** [comment]
Thanks for finding this! I'll start the review process. Hopefully we can release a new beta tomorrow. Thanks again!

**Comment by FantasticFiasco** [comment]
v8.0.0-beta.4 has [now been released on nuget](https://www.nuget.org/packages/Serilog.Sinks.Http/8.0.0-beta.4). Please let me know if it fixes you issue.
