### ISSUE TITLE
JsonGzipHttpClient does not work

### ISSUE THREAD

**Issue by AntonSmolkov** [FantasticFiasco/serilog-sinks-http#190]
**Describe the bug**
When using JsonGzipHttpClient, sink always send empty messages

**To Reproduce**
`httpClient: new JsonGzipHttpClient(CompressionLevel.Fastest)`

**Expected behavior**
Sink must send gzip-compressed messages

**Screenshots**

**Comment by FantasticFiasco** [comment]
Thanks for reporting this!

I will merge your PR and create a new release, add you to the list of contributors in `README.md`, but I've also created #192 to prevent the issue from happening again.

**Comment by FantasticFiasco** [comment]
v8.0.0-beta.6 has now [been released on nuget.org](https://www.nuget.org/packages/Serilog.Sinks.Http/8.0.0-beta.6).

Thanks again for reporting this!

**Comment by AntonSmolkov** [comment]
Great! Thanks for fast response
