### ISSUE TITLE
Incompatibility with asp.net core 2.x

### ISSUE THREAD

**Issue by AntonSmolkov** [FantasticFiasco/serilog-sinks-http#208]
**Describe the bug**
1) Serilog.Sinks.Http 7.2.0/8.0.0-beta.7 both can't be installed to asp.net core 2.x on dotnet 2.x project with error message:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.Extensions.Configuration. Install/reference Microsoft.Extensions.Configuration 3.1.9 directly to project netcore21aspnetcore to resolve this issue. 
 netcore21aspnetcore -> Serilog.Sinks.Http 7.2.0 -> Microsoft.Extensions.Configuration (>= 3.1.9) 
 netcore21aspnetcore -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Configuration (>= 2.1.1 && < 2.2.0).	netcore21aspnetcore	C:\Users\user\RiderProjects\ComatCheck\netcore21aspnetcore\netcore21aspnetcore.csproj	1	

```

2) Serilog.Sinks.Http 8.0.0-beta.7 with asp.net core 2.x on net46+ project causes runtime exception during start:
```
System.TypeLoadException: Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Net.Http.Headers.DateTimeFormatter.ToRfc1123String(DateTimeOffset dateTime, Boolean quoted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.DateHeaderValueManager.SetDateValues(DateTimeOffset value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.DateHeaderValueManager.OnHeartbeat(DateTimeOffset now)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat()
```
(Additional context - https://github.com/dotnet/aspnetcore/issues/27986)

.
**To Reproduce**
First case:
```
dotnet new webapp --framework netcoreapp2.1 -o superproj
cd  superproj
dotnet add package serilog.sinks.http
```
Second case:
Visual Studo => New Project => ASP.NET Core Web App => "Run on .NET Framework" checkbox => Add "Serilog.Sinks.Http 8.0.0-beta.7" => Run project

**Reason**
Reason  for both cases- too high lower version of Microsoft.Extensions.Configuration.

**Comment by FantasticFiasco** [comment]
Hi @AntonSmolkov!

I'll look into this issue and the pull request tomorrow. Thanks for reporting it!

**Comment by AntonSmolkov** [comment]
@FantasticFiasco  Thanks! Please consider releasing a new beta. Really need this sink for asp.net core 2.

**Comment by FantasticFiasco** [comment]
I've started looking into this issue, and it seems that both cases relate to .NET Core 2.1, would you say that is correct?

First off, please accept my apologies for not finding and fixing this issue sooner, but as it currently stand where .NET Core 2.1 will become unsupported in just a couple of weeks ([source](https://dotnet.microsoft.com/platform/support/policy)), it would provide diminishing value to fix this now, and then remove support for .NET Core 2.1 in just a couple of weeks. Wouldn't you agree?

Would an alternative approach to "solving" this issue be to upgrade your application to .NET Core 3.1 (also an LTS version), thus remaining on a supported .NET version, while in the same time provide a fix for this issue? What are your thoughts?

**Comment by FantasticFiasco** [comment]
I'll look into this issue more tomorrow. I'll have to read up on how the referenced versions are resolved.

**Comment by AntonSmolkov** [comment]
> and it seems that both cases relate to .NET Core 2.1,

Unfortunately it isn’t. Second case i described relates to asp.net core 2.1 for classic .NET Framework 4.8. 
EOL of this asp.net core 2.1 == EOL of Net 4.8 == EOL of Windows 10 == 2025.

> Note: support for ASP.NET Core 2.1 on .NET Framework matches the support policy of the .NET Framework.

 [source](https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/)

And this is the actual case my teammates met. 
We steal have windows only legacy apps which bound to third-party windows-only libraries.

**Comment by AntonSmolkov** [comment]
The only reason i had concerns about asp.net core 2.1 for .net core 2.1(not classic 4.8) is that this library declares compatibility level of .net standard 1.3. 
This is pretty broad level which supports even .net core 1.0
https://dotnet.microsoft.com/platform/dotnet-standard#versions

**Comment by FantasticFiasco** [comment]
Thanks for the clarification!

I'll have to read up on this. I would like to support the targets Microsoft are supporting, and still depend on the latest version of `Microsoft.Extensions.Configuration` for each of these specific targets. Better yet would be to have tests that makes sure this is maintained during future development.

**Comment by AntonSmolkov** [comment]
@FantasticFiasco 

>  I would like to support the targets Microsoft are supporting, and still depend on the latest version of Microsoft.Extensions.Configuration

I think the only way to achieve this completely is multitargeting to each of the supported platforms and using conditional nuget references. E.G. 
```xml
<ItemGroup Condition="'$(TargetFramework)' != 'netcoreapp3.1'">
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1" />
  </ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' != 'net5.0'">
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0" />
  </ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' != 'net4.8'">
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0" />
 </ItemGroup>
```
If you want to continue using .net standart, than using **minimum requiered** version is the only way.
The only drawback of this approach is that sometimes user will have to add appropriat version of Microsoft.Extensions.Configuration explicitly. But he will use the latest appropriat version in any case.
![image](https://user-images.githubusercontent.com/5318028/128639024-54cb77f6-7036-4a0a-9e99-3129f8d49dd2.png)

**Comment by FantasticFiasco** [comment]
Yes, it's not an uncomplicated problem to support `Microsoft.Extensions.Configuration` it seems. I will investigate how other packages manages to support it.

Another solution I've been thinking about the last couple of days is to remove the transient dependency altogether. That instead of passing in a `IConfiguration` implementation to the sink, one could pass a `Func<string, string>`, which basically has the same functionality as the `Microsoft.Extensions.Configuration` package.

**Comment by AntonSmolkov** [comment]
> Another solution I've been thinking about the last couple of days is to remove the transient dependency altogether. That instead of passing in a IConfiguration implementation to the sink, one could pass a Func<string, string>, which basically has the same functionality as the Microsoft.Extensions.Configuration package

But then, it would be probably impossible to implement what is described in wiki:

> configuration - Configuration passed to httpClient. Parameter is either manually specified when configuring the sink in source code or automatically passed in when configuring the sink using Serilog.Settings.Configuration.

BTW i noticed that the latest version of **Serilog.Settings.Configuration** for .NETStandard 2.0 also has transitive dependency to Microsoft.Extensions.Configuration.Abstractions >= **2.0**. So it's:
```Serilog.Settings.Configuration 3.2.0 -> Microsoft.Extensions.Options.ConfigurationExtensions (>= 2.0.0) -> Microsoft.Extensions.Configuration.Abstractions (>= 2.0.0)```
Thus, i think it would be totally valid to use the same approach for this package too.

**Comment by AntonSmolkov** [comment]
Changed Microsoft.Extensions.Configuration to Microsoft.Extensions.Configuration.Abstractions in my PR.

**Comment by FantasticFiasco** [comment]
I've released v8.0.0-beta.8 based on your PR. Can you verify that it works as expected? Thanks!

**Comment by AntonSmolkov** [comment]
Both cases described in this issue are now work correctly. Thanks, @FantasticFiasco!
And thank you for the release!

**Comment by AntonSmolkov** [comment]
By the way - as far as i understand, there is no reason for building the library for three versions of .net standard (1.3, 2.0, 2,1) because 1.3 subsets the APIs list of 2.0 and 2.1.
So building only for 1.3 must be sufficient, especially now, when you deleted the shim. 
What do you think?

**Comment by FantasticFiasco** [comment]
.NET Standard 1.3 support was added due to the [Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/), but I now see that the guidance has been updated with [the release of .NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting). I'll create a new issue making sure that we continue to follow the guidance.
