### ISSUE TITLE
Whats the timeline for a new nuget?

### ISSUE THREAD

**Issue by nshayanfar** [FantasticFiasco/serilog-sinks-http#218]
Hi,

Its been some time and there have been some really useful changes on the library, specially i am looking forward to the new signature for "DurableHttpUsingTimeRolledBuffers". Whats the timeline for new nuget?

**Comment by nshayanfar** [comment]
got it

**Comment by FantasticFiasco** [comment]
It's a valid question, and one I cannot give an definite answer, but since you closed it I assume you found the [v8 project dashboard](https://github.com/FantasticFiasco/serilog-sinks-http/projects/1)?
