### ISSUE TITLE
Getting Properties on elk

### ISSUE THREAD

**Issue by revocengiz** [FantasticFiasco/serilog-sinks-http#22]
### Hi, im trying to use seri log with ELK stack by help of your project. 
I'm using Asp.Net Core 2.0.0-preview2-final
  
### Here is the how i use
 ILogger log = new LoggerConfiguration()
                    .Enrich.WithProperty("CorrelationId", Guid.NewGuid().ToString ())
                    .Enrich.FromLogContext()
                    .MinimumLevel.Verbose()
                    .WriteTo.DurableHttp("http://localhost:31311") // logstash uri
                    .CreateLogger()
                    .ForContext<httpsink.Program>();
When i try to log like below, it won't parse properties to kibana ui.
 log.Information("The {user} has access to {resource}", "cengiz","some resource info");
Here is the result
![sink1](https://user-images.githubusercontent.com/6932535/29070698-27a72fa8-7c49-11e7-84f5-9e506350c281.PNG)

When i log same message directly to elasticsearch instead of logstash with "serilog.sinks.elasticsearch"
It produces to fileds.

Here is the result
![sink2](https://user-images.githubusercontent.com/6932535/29070825-8c112638-7c49-11e7-8c5f-626c38572c94.PNG)

Do you have any suggestions?
By the way when sending batch logs , all item send as a one message as a string. Is there way to prevent this?
Thanks in advance.

**Comment by FantasticFiasco** [comment]
I'll take a look at it tonight.

Would it be possible for you to create a small repo displaying the problem? Preferably with the Elastic stack in Docker containers.

**Comment by FantasticFiasco** [comment]
> By the way when sending batch logs , all item send as a one message as a string. Is there way to prevent this?

Absolutely, you can customize both [event formatters](https://github.com/FantasticFiasco/serilog-sinks-http#event-formatters) and [batch formatters](https://github.com/FantasticFiasco/serilog-sinks-http#batch-formatters), making it possible for you to customize the data sent over the network.

**Comment by FantasticFiasco** [comment]
I'm in the process of setting up a Elastic stack repo, but it will take some days. Please bear with me.

**Comment by revocengiz** [comment]
Thank you for quick response. I created a respository which contains ELK stack in docker (i cloned from [docker-elk](https://github.com/deviantony/docker-elk) ) and .net core samples one for sinks to elestik search directly and another one for sinks via httpsink
[my sample repo](https://github.com/revocengiz/Elk)

**Comment by FantasticFiasco** [comment]
Nice! I'll take a look at it!

**Comment by FantasticFiasco** [comment]
I've started to look at the problem from the perspective of configuring logstash to parse the log events sent from Serilog, and have kind of figured it out. Now I would like to look at it from the perspective of Serilog, to see if I can configure the Serilog formatters to send JSON that natively have support in logstash.

Either way, do I have push permissions to your repo, because either way I would like to help you out in your repository.

**Comment by revocengiz** [comment]
I added you as a collaborator. I think this should be enough. I've never done something similar before ^__^

**Comment by FantasticFiasco** [comment]
You did everything right. I got the invitation and have accepted.

One question though: when it comes to the property names displayed in Kibana, the names chosen by the Elasticsearch sink is not identical to my sink. As an example, in the Elasticsearch sink a property would be called `fields.user` while the same in my sink would be called `Properties.user` or something similar.

Is it important to you that the names in Kibana is a 100% match to those defined by the Elasticsearch sink?

**Comment by revocengiz** [comment]
I'm absolutely fine with Properties.user as long as all parmeters starts with same word. Fields.xxx or Properties.xxx.

**Comment by FantasticFiasco** [comment]
I've updated your repo with two commits. The first is configuring logstash to prepare for JSON formatted log events on the HTTP input, and the second commit is using a pre-release of this sink that improves compatibility with the Elastic stack.

Can you please try it out, and if everything is to your pleasing, I'll release a new official version instead of the pre-release.

**Comment by revocengiz** [comment]
It's work perfectly fine both console app and Asp.Net Core 2.0.0-preview2-final. 
I really appreciate all your help. ^__^

**Comment by FantasticFiasco** [comment]
Perfect! Expect an official release within 24 hours.

Thanks for bringing this issue to my attention, these changes will increases the value of this sink.

**Comment by FantasticFiasco** [comment]
v4.1.0 is now official on NuGet.
