### ISSUE TITLE
Change non-durable sink to require an explicit queue limit, or null for no limit

### ISSUE THREAD

**Issue by seruminar** [FantasticFiasco/serilog-sinks-http#245]
**Is your feature request related to a problem? Please describe.**
By default the `Http` extension method registers a non-durable sink with an unlimited internal queue, optionally limited by the parameter `queueLimit`. In a long-running high-volume application, the default unlimited queue continuously grows and eventually takes up a significant portion of memory. In a memory-restricted environment like a Docker container, too much memory allocation can cause a crash.

**Describe the solution you'd like**
A solution is to change the method signature by removing the default value of that parameter (where the default value `null` means that the queue is unlimited). This will ensure that the user will need to explicitly pass `null` to opt-in to an unlimited queue, or choose a queue limit that makes sense for their use case.

**Describe alternatives you've considered**
The problem is solved by knowing the internal structure of the queue, or by knowing the parameter exists and specifying it. However, anyone who uses that extension method and skips the optional parameter may experience memory problems and not know that a queue used for logging is the cause.

**Additional context**
Previous discussion in #203

**Comment by FantasticFiasco** [comment]
The parameter has now been promoted to be mandatory. A new pre-release [has been published to nuget.org](https://www.nuget.org/packages/Serilog.Sinks.Http/8.0.0-beta.11). Please let me know if it doesn't meet you expectations.
