### ISSUE TITLE
DurableHttpSink sometimes split log event and sometime merge other log event in-between 

### ISSUE THREAD

**Issue by rgautam08** [FantasticFiasco/serilog-sinks-http#249]
**Describe the bug**
While saving the log in buffer file log event gets split/Merge in-between   sometime.
This problem is coming when our buffer file location is in network path , local machine folder path working fine.

Http sink Current version :- V7.2.0
Integrated Framework:- .net 4.7.2
Buffer file location :- Network path
Used http sink :- Durable file size rolled HTTP sink

Sample log:-

.83.247.167","LogVersion":"1","ApplicationName":"TestApp","ServerIp":"0.0.0.0",,"RoleName":"TestRole"}}
{"@t":"202{"@t":"2022-02-28T13:24:36.8107161Z","@m":"","@p":{"ApplicationName":"TestApp",","@s":"bcdaf2ebc8e1b{"@t":"2022-02-28T13:24:37.4750734Z","@m":"","@p":{"ApplicationName":"TestApp",,"RoleName":"TestRole"@t":"2022-02-28T13:24:40.3836657Z","@m":""}}

Like we have multiple broken logs in the buffer file.

**To Reproduce**
Integrated this module to .net framework and added some enrichers  like client ip, server ip.
and set buffer file path to network location of different machine like "\\machine1\log"
and generates the logs from integrated application .

**Expected behavior**
Valid log should be created in buffer file.

also look for  similar bug that is with old version: https://github.com/FantasticFiasco/serilog-sinks-http/issues/54

**Comment by FantasticFiasco** [comment]
Hi @rgautam08.

Would you be able to show the configuration of the sink and the enrichers, although I assume that the enrichers have nothing todo with the issue in question? If you are able, please present the most minimal sink configuration that still produces the errors in the buffer files.

**Comment by rgautam08** [comment]
public Logger Create(LoggerConfiguration loggerConfiguration = null)
        {
           loggerConfiguration = loggerConfiguration ?? new LoggerConfiguration();
            loggerConfiguration
               .WriteTo
               .DurableHttpUsingFileSizeRolledBuffers(
               bufferFileSizeLimitBytes: 5242880,
               bufferFileShared: true,
               requestUri:"http://testweb.com",
               bufferBaseFileName: "TestBufferfile",
               batchPostingLimit: 1000,
               period: 2,
               batchFormatter: new LogEventBatchFormatter(),
               textFormatter: new LogEventBatchFormatter(),
               httpClient:  new SerilogHttpClient(),
               retainedBufferFileCountLimit: null);
          return loggerConfiguration.CreateLogger();
        }

this is configuration we are using. do you see any improvement ?

**Comment by FantasticFiasco** [comment]
A couple of things to clarify in your configuration.

1. The argument `bufferBaseFileName` points to the current working directory. Is this correct? I was assuming to see `bufferBaseFileName` pointing to a network path, as you described in the issue.
2. Shouldn't the argument `period` be of type `TimeSpan`?
3. Both argument `batchFormatter` and `textFormatter` seem to instantiate a class of type `LogEventBatchFormatter`. Is this correct? Formatting batches and individual events are not the same thing.

**Comment by rgautam08** [comment]
Hi
 1. No, we have file location in network path like "\\testserver.com\log\TestBufferfile". as i described in bug for local path working fine.
2. Yes, period is TimeSpan, we have setup to 2 second , this is also a default value but we given possibility to change.
3.  Sorry my mistake copy paste issue, textFormatter is having instance of textFormatter only.  like below , 
           
    textFormatter: new TextFormatter().

**Comment by rgautam08** [comment]
hi investigated more this issue and found broken log has time delayed, means latest log posted first and old log come later.
if we look the below log first row has latest time span and in last row, we have older time span in-between we have broken log.

 "@t":"2022-03-03T06:30:43.9521156Z"
:"test"}} // broken log
"@t":"2022-03-03T06:31:43.8801827Z"

**Comment by FantasticFiasco** [comment]
This sink is relying on [Serilog.Sinks.File](https://github.com/serilog/serilog-sinks-file) as the underlying mechanism of saving log events in buffer files. According to an issue in Serilog.Sinks.File there might be a problem with [atomic writes on network shares](https://github.com/serilog/serilog-sinks-file/issues/99#issuecomment-488462319).

Do you have the option to save the buffer files on your local disk instead of on the shared drive? What environment are you running in?

**Comment by janichirag11** [comment]
Are you planning to use Serilog.Sinks.Async in the latest version to solve similar issues for network file writing.
Also, any planned date to release date for v8?

**Comment by FantasticFiasco** [comment]
No, there are no plans to officially support writing to network shares. Regarding release v8, I think we can get there within the month.
