### ISSUE TITLE
custom http client version 8.0

### ISSUE THREAD

**Issue by tipasergio** [FantasticFiasco/serilog-sinks-http#254]
in custom HTTP client implementation stream content comes with an empty timestamp and log level properties

**Comment by FantasticFiasco** [comment]
Thanks for reporting this issue! I'll look into it in the upcoming days.

**Comment by FantasticFiasco** [comment]
Do you mean [the implementation in the wiki](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Custom-HTTP-client#example-the-basic-authenticated-http-client) or do you mean that a custom implementation in your codebase is not working as expected? The the latter, are you using the HTTP sink (`Http`), the durable file size rolled sink (`DurableHttpUsingFileSizeRolledBuffers`) or the durable time rolled sink (`DurableHttpUsingTimeRolledBuffers`)?

**Comment by FantasticFiasco** [comment]
Closed due to inactivity.
