### ISSUE TITLE
Add ability to select the extension of log files on durability

### ISSUE THREAD

**Issue by RuslanLatsina** [FantasticFiasco/serilog-sinks-http#283]
There is an issue with supporting compatibility between different sinks. As an example Elastic.sink has json extension, but HTTP.sink - txt

It will be nice to have the ability to override the extension

**Comment by FantasticFiasco** [comment]
Hi @RuslanLatsina. Can you elaborate a bit more on why you find it problematic that different sinks create files with different file endings?

**Comment by RuslanLatsina** [comment]
Hi @FantasticFiasco , I`m trying to inject http.Sink with elastic.sink into project but found that when I`m trying switch destination, bookmark file is not trying to be updated by itself. And here i got an issue when bookmark file contains invalid last-file extension, the transfering is not continued.

**Comment by FantasticFiasco** [comment]
So you are sending log events to Elasticsearch using [Serilog.Sinks.Elasticsearch](https://www.nuget.org/packages/serilog.sinks.elasticsearch/) and you use this sink to send the same log events to another log server. Is this correct?

>  ...bookmark file is not trying to be updated by itself

I don't know what you mean here. Can you explain a bit more?

> ...bookmark file contains invalid last-file extension,

What is a "last-file extension"?

For reference, the reason why we use *txt* files is described in #169.

**Comment by RuslanLatsina** [comment]
Hi @FantasticFiasco ,
yeah, you are right. My c# desktop application gets the destination log server from API. And if we change the destination from ElasticSearch to another LogServer, which sends logs through API, **the logs are not sent anymore.**

I observed that on LogProvider change, the log files started to have another file extension. And if Bookmark file contains an invalid extension, the logs are not sent to another LogServer. But if I clean bookmark file content and remove all files with ".json" extension - the logs are sent successfully again.
![image](https://user-images.githubusercontent.com/20533082/191257366-78fe0721-631c-48b3-a20f-7c1434918d7c.png)

**Comment by FantasticFiasco** [comment]
Is the bookmark file and the buffer files shared between Serilog.Sinks.Elasticsearch and this sink? I.e. are both sinks relying on the same set of files, or do they have their individual set of files?

**Comment by FantasticFiasco** [comment]
Close due to inactivity.
