### ISSUE TITLE
Add SSL Support

### ISSUE THREAD

**Issue by jceddy** [FantasticFiasco/serilog-sinks-http#288]
**Is your feature request related to a problem? Please describe.**

I am attempting to use the Http sink to send data to logstash on another server. Logstash on the remote server only allows SSL connections.

**Describe the solution you'd like**

Ability to specify using SSL and what certificates to use.

**Describe alternatives you've considered**

I have considered writing my own sink to accomplish this.

**Comment by jceddy** [comment]
I am looking into creating a custom HttpClient for this functionality.

**Comment by FantasticFiasco** [comment]
Hi @jceddy, you're on the right track. The `IHttpClient` interface is really slim and will not prevent you from implementing TLS/SSL support.
