### ISSUE TITLE
Add support for durable sink

### ISSUE THREAD

**Issue by harvinders** [FantasticFiasco/serilog-sinks-http#3]
It would be great if we have support for durable sink something similar to `Serilog.Sinks.Seq `

**Comment by FantasticFiasco** [comment]
This is a very good proposal, and would surely help with network connectivity issues. I can assume that logs get lost if connection between log source and destination is unreliable.

I will look into the issue during the upcoming week, the durable nature of the Seq sink doesn't look like it would be impossible to get inspiration from.

**Comment by FantasticFiasco** [comment]
The implementation of the durable sink is coming to its end, expect a new release within a couple of days.

Heads up, it will be a new major version due to breaking changes, but it should only take you a minute or so to make your code compile again.

**Comment by FantasticFiasco** [comment]
[Version 3.0.0](https://www.nuget.org/packages/Serilog.Sinks.Http/3.0.0) has now been released!

Virtual 🍰 for everyone!
