### ISSUE TITLE
Ingest fetch call from blazor does not pass CORS check

### ISSUE THREAD

**Issue by mruch2** [FantasticFiasco/serilog-sinks-http#301]
I have a blazor PWA app and am using the http sink to pass my logs to my api site.

.Net Core 7.0.2 for both Client and Server

I am getting this error:
"Access to fetch at 'https://localhost:44378/ingest' from origin 'https://localhost:5001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

Keep in mind all my other endpoints for my API requests are exactly the same. I have kept the setup for http pretty standard and also the api side.

Blazor Serilog Program.cs

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.ControlledBy(levelSwitch)
    .Enrich.WithProperty("InstanceId", Guid.NewGuid().ToString("n"))
    .Enrich.WithProperty("Application", $"{Assembly.GetExecutingAssembly().GetName()}")    
    .WriteTo.BrowserHttp(endpointUrl: $"{apiSettings.apiPath}/ingest", controlLevelSwitch: levelSwitch)    
    .CreateLogger();

builder.Logging.AddSerilog();

I also tried binding with this:
//builder.Services.AddLogging(loggingBuilder => loggingBuilder.AddSerilog(dispose: true));
Same result.

Server API side
Log.Logger = new LoggerConfiguration()
    .WriteTo
    .MSSqlServer(
        connectionString: Configuration["ConnectionStrings:MyDB"],
        sinkOptions: new MSSqlServerSinkOptions
        {
            TableName = "SerilogLog",
            BatchPostingLimit = 1000,
            BatchPeriod = TimeSpan.FromSeconds(30),
            AutoCreateSqlTable = false
        })
    .CreateLogger();

app.UseSerilogIngestion();
app.UseSerilogRequestLogging();

The API site successfully logs all my other API calls from the same source to the same endpoint just fine into table SerilogLog.

Any insight on what I may have setup wrong would be appreciated.

**Comment by FantasticFiasco** [comment]
Hi @mruch2. CORS is usually a thing in requests from a web browser, isn't it? I know nothing about Blazor applications, is you app running in a web browser environment?

**Comment by mruch2** [comment]
Correct, CORS is only found in browsers but the only call that fails the CORS check is the one that Serilog is making when the interval to push logging up kicks off. I can't figure out why. 

So Seilog batch send is what is throwing the error everytime it kicks off.

**Comment by mruch2** [comment]
@FantasticFiasco 

Here is the error from serilog following the cors error.

![image](https://user-images.githubusercontent.com/7441786/214132442-2ae8dcac-23d6-4c25-8a47-8a2ad75a78f0.png)


dotnet.7.0.2.tt5z2s8frk.js:5 
       POST https://localhost:44378/ingest net::ERR_FAILED
(anonymous) @ dotnet.7.0.2.tt5z2s8frk.js:5
_t @ dotnet.7.0.2.tt5z2s8frk.js:5
ia @ dotnet.7.0.2.tt5z2s8frk.js:5
_bound_js_INTERNAL_http_wasm_fetch @ _bound_js_INTERNAL_http_wasm_fetch:13
Ss @ dotnet.7.0.2.tt5z2s8frk.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.2.tt5z2s8frk.js:14
$func313 @ dotnet.wasm:0x1d40d
$func283 @ dotnet.wasm:0x1c906
$func221 @ dotnet.wasm:0xdff6
$func220 @ dotnet.wasm:0xce95
$func8115 @ dotnet.wasm:0x1a2195
$func2054 @ dotnet.wasm:0x85bba
$func2059 @ dotnet.wasm:0x86222
$mono_set_timeout_exec @ dotnet.wasm:0x1bb377
Module._mono_set_timeout_exec @ dotnet.7.0.2.tt5z2s8frk.js:14
mono_wasm_set_timeout_exec @ dotnet.7.0.2.tt5z2s8frk.js:5
setTimeout (async)
ya @ dotnet.7.0.2.tt5z2s8frk.js:5
_mono_set_timeout @ dotnet.7.0.2.tt5z2s8frk.js:14
$func8523 @ dotnet.wasm:0x1bb3ff
$func313 @ dotnet.wasm:0x1d3e9
$func283 @ dotnet.wasm:0x1c906
$func221 @ dotnet.wasm:0xdff6
$func220 @ dotnet.wasm:0xce95
$func8115 @ dotnet.wasm:0x1a2195
$func2054 @ dotnet.wasm:0x85bba
$func2059 @ dotnet.wasm:0x86222
$mono_set_timeout_exec @ dotnet.wasm:0x1bb377
Module._mono_set_timeout_exec @ dotnet.7.0.2.tt5z2s8frk.js:14
mono_wasm_set_timeout_exec @ dotnet.7.0.2.tt5z2s8frk.js:5
setTimeout (async)
ya @ dotnet.7.0.2.tt5z2s8frk.js:5
_mono_set_timeout @ dotnet.7.0.2.tt5z2s8frk.js:14
$func8523 @ dotnet.wasm:0x1bb3ff
$func313 @ dotnet.wasm:0x1d3e9
$func283 @ dotnet.wasm:0x1c906
$func221 @ dotnet.wasm:0xdff6
$func220 @ dotnet.wasm:0xce95
$func8115 @ dotnet.wasm:0x1a2195
$func2054 @ dotnet.wasm:0x85bba
$func2059 @ dotnet.wasm:0x86222
$mono_set_timeout_exec @ dotnet.wasm:0x1bb377
Module._mono_set_timeout_exec @ dotnet.7.0.2.tt5z2s8frk.js:14
mono_wasm_set_timeout_exec @ dotnet.7.0.2.tt5z2s8frk.js:5
blazor.webassembly.js:1 2023-01-23T19:29:21.5850000Z Exception while emitting periodic batch from Serilog.Sinks.BrowserHttp.BrowserHttpSink: System.Net.Http.HttpRequestException: TypeError: Failed to fetch
blazor.webassembly.js:1  ---> TypeError: Failed to fetch
blazor.webassembly.js:1    --- End of inner exception stack trace ---
blazor.webassembly.js:1    at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
blazor.webassembly.js:1    at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
blazor.webassembly.js:1    at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|55_0(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
blazor.webassembly.js:1    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
blazor.webassembly.js:1    at Serilog.Sinks.BrowserHttp.BrowserHttpSink.EmitBatchAsync(IEnumerable`1 events)
blazor.webassembly.js:1    at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

**Comment by mruch2** [comment]
Hi @FantasticFiasco, I am sure you are pretty busy. Was wondering if you had a moment to look over what I posted here?

**Comment by FantasticFiasco** [comment]
Does Blazor feature some kind of HTTP API that one is supposed to use when running a Blazor app? The requests that succeed, how are they sent? Are they sent from an ordinary `HttpClient` instance?

**Comment by mruch2** [comment]
@FantasticFiasco yes it does. Is there a way to have serilog use the internal httpClient?

**Comment by FantasticFiasco** [comment]
Yes, see [the wiki](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Custom-HTTP-client) for more information. What you probably are looking for is to inject the Blazor HTTP client into the sink.

**Comment by mruch2** [comment]
So I am following this for the Blazor WASM setup.

https://github.com/nblumhardt/serilog-sinks-browserhttp

The sink you are referring to is different. From the documentation the one I listed is intended for Blazor WASM.

**Comment by mruch2** [comment]
@FantasticFiasco after some significant testing. I think the issue is on the API side. The ingest method I don't think is returning the header items to pass the CORS check client side. How do I pass in my own HttpClient for the ingest method to use?

I now have the HttpClient working for the client side and the bearer token works as well.

**Comment by mruch2** [comment]
@FantasticFiasco  The ingest endpoint from the ASPNet instance does not add the allowed origins header to the response. So the browser is failing it on the pre-flight check because the header is missing. How do I configure the ingest endpoint to supply a header?

**Comment by mruch2** [comment]
@FantasticFiasco I proved out this theory and it works. I took the ingestion code and modified what I needed for use within a controller that I can pass the CORS config into.
`
    [Authorize]
    [HttpPost]
    [Route("/[controller]/ingest")]
    public async Task<IActionResult> SubmitSupportRequest()
    {

        try
        {
            var reader = new StreamReader(Request.Body);

            var line = await reader.ReadLineAsync();
            while (line != null)
            {
                if (!string.IsNullOrWhiteSpace(line))
                {
                    try
                    {
                        var jObject = JsonConvert.DeserializeObject<JObject>(line);
                        var evt = LogEventReader.ReadFromJObject(jObject);
                        _logger.Write(evt);
                    }
                    catch (Exception ex)
                    {
                        SelfLog.WriteLine("Failed to deserialize event from {0}: {1}", Request.HttpContext.Connection.RemoteIpAddress, ex);
                    }
                }

                line = await reader.ReadLineAsync();
            }

            return Ok();

        }
        catch (Exception)
        {
            return BadRequest();
        }


    }`

**Comment by FantasticFiasco** [comment]
> So I am following this for the Blazor WASM setup.
> 
> https://github.com/nblumhardt/serilog-sinks-browserhttp
> 
> The sink you are referring to is different. From the documentation the one I listed is intended for Blazor WASM.

The link I gave you is a link to the wiki of this repository, a repository that contains `Serilog.Sinks.Http`. If you're having issues with another sink you should open the issue in that sink.
