### ISSUE TITLE
Allow Option For Archiving Rolled Buffer Files

### ISSUE THREAD

**Issue by AustinAndersonTxm** [FantasticFiasco/serilog-sinks-http#306]
The log ingest endpoint I'm trying to send to will reject logs older than ~2 days, so the roll interval is rather short, ideally there would be some way to archive those, such as through adding https://github.com/cocowalla/serilog-sinks-file-archive on the buffer sink.

**Comment by FantasticFiasco** [comment]
Hi @AustinAndersonTxm. Can you tell me more about the environment you run in and the circumstances when this occurs?

Is this happening when you for some reason is unable to send the logs for ~2 days, and then when you finally can the log server is rejecting them, and that counts as a trigger for this sink to resend the same old log events again?
