### ISSUE TITLE
Feature request: Implement durable behavior

### ISSUE THREAD

**Issue by lhaussknecht** [FantasticFiasco/serilog-sinks-http#31]
It would be nice to a have an option to make the sink durable. 

A good example of implementing this is the loggly sink. https://github.com/serilog/serilog-sinks-loggly/blob/dev/src/Serilog.Sinks.Loggly/Sinks/Loggly/HttpLogShipper.cs

**Comment by FantasticFiasco** [comment]
Hi lhaussknecht!

You are in luck, the sink can be configured to be [durable](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Durable-HTTP-sink), a feature that was implemented in v3.0.0.

I will look into the visibility of the durability, it could be the case that the durable options isn't stated clear enough.

**Comment by FantasticFiasco** [comment]
I've updated [README.md](https://github.com/FantasticFiasco/serilog-sinks-http/) to mention durability, and have in the wiki added example code using the [HTTP sink](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/HTTP-sink) and the [durable HTTP sink](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Durable-HTTP-sink).

Thanks for bringing this to my attention.

**Comment by lhaussknecht** [comment]
Hey cool. Yeah indeed I haven't looked at version 3. Good to see the updated Readme! 
Cheers!
