### ISSUE TITLE
Recommended for Logstash filter config (in ELK)

### ISSUE THREAD

**Issue by polarbit** [FantasticFiasco/serilog-sinks-http#34]
Hi, thank you very much for this package, we started to use it.

As you know, this package batches log events and sends logs as a single log request into Logstash.
Logs are batched as json array  as string  & and put into the "message" field of the http batch log reqeust to Logstash. Then logstash sends this request to elasticsearch etc.

The problem is, Kibana/Elastic see these log events in the "message" field just a simple text.

So we tried some Logstash filters and splitted these batched-log-events as seperate logs with following Logstash configuration.

I just wanted to share our findings with anyone who may be had same problem & interest in splitting batched logs into seperate logs in Logstash.

```yaml
input {
        tcp {
                port => 5000
        }
        http {
                port => 8080
        }
}

filter {
        json {
                source => "message"
        }
        mutate {
                update => { "message" => "..." }
        }
        split {
                field => "events"
        }
}

output {
        elasticsearch {
                hosts => "elasticsearch:9200"
        }
}
```

Best regards.

**Comment by FantasticFiasco** [comment]
Awesome, thanks for contributing this information back to the community! This will surely help all other developers wishing to send their log events to the Elastic Stack.

I've set up a project called [serilog-sinks-http-elastic-stack](https://github.com/FantasticFiasco/serilog-sinks-http-elastic-stack) that demonstrates how one would integrate Serilog with the Elastic Stack. I've linked the project from the [README.md](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/README.md), but perhaps the reference is lost among the other links? What do you think?

Could you take a look at [serilog-sinks-http-elastic-stack](https://github.com/FantasticFiasco/serilog-sinks-http-elastic-stack), and if you find that your configuration is better than the one I am using, I would like to adapt my configuration to match your.

**Comment by polarbit** [comment]
I think I missed your sample project link. Your using of just the line "codec => json"  is very simpler & better of course. I did not know that.

Thank you very much. 👍
