### ISSUE TITLE
Sending logs to MS's LogAnalyzer

### ISSUE THREAD

**Issue by justSteve** [FantasticFiasco/serilog-sinks-http#35]
### Step 1: Describe your environment

* Operating system?
Core 2 Web App deployed to Azure App Service
### Step 2: Describe the problem
Authenticate and send log messages to Log Analyzer as per: [Send data to Log Analytics with the HTTP Data Collector API](https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-collector-api).

Where your sample config code includes a 'requestUri' Arg, LA is expecting a complete set of credentials and headers. How can these properties be populated with this lib?

**Comment by FantasticFiasco** [comment]
The sink supports custom implementations of a HTTP client, which means that you should be able to set your headers as you please. The payload format is also fully configurable, which means whatever format LA expects, you should be able to provide with some configuration.

**Comment by justSteve** [comment]
Thanks for the quick reply - makes sense. So the HTTP client would be constructed during the page's lifetime as opposed to being placed in the config.

**Comment by FantasticFiasco** [comment]
Can you elaborate on what you mean by _page_? I most situations the logs are sent from the backend, but you seem to indicate that the logs will be sent from the frontend?

**Comment by justSteve** [comment]
Sorry for the confusion - a poor choice of words. I've been focused on an MVC app and spend most of my time logging within methods that produce 'pages'.

**Comment by FantasticFiasco** [comment]
Ok, it seems like server generated HTML seems to get some traction again, always nice to see!

Regardless of whether the HTML is generated on the server or the app is a SPA, I would advice to setup the logging once when the web server is started.  Nicholas Blumhardt, the author of Serilog, has written an [article](https://nblumhardt.com/2017/08/use-serilog/) describing how one would setup logging in .NET Core. Configuring Serilog.Sinks.Http should be done here as well, thus your custom implementation of a HTTP client should be defined here as well, and the lifetime of that HTTP client would match the lifetime of the web server, not the lifetime of the page rendering.

Does this answer your question?

**Comment by justSteve** [comment]
Many thanks for the details and the links. On the topic of configuring
logging (and specifically to the DI perspective) you might find this
interesting: https://stackify.com/net-core-loggerfactory-use-correctly/

**Comment by FantasticFiasco** [comment]
Nice, thanks! I will definitely read that one.

Hope your endeavour with Serilog turn out to be successful. If you are having any issues with this sink, please get in touch with me and we'll try to work it out.

Have a nice weekend!
