### ISSUE TITLE
Configuring Logstash Similar to Elasticsearch Sink's Index Format Property

### ISSUE THREAD

**Issue by giangcoi48k** [FantasticFiasco/serilog-sinks-http#357]
I am using Http Sink to send logs to Logstash from multiple applications. For each application, I want to send logs to a separate index. Elasticsearch Sink provides a configuration property to accomplish this: IndexFormat = $"Logs-{env}-{DateTime.Now:yyyy-MM}". Is there a way to configure Http Sink similarly to achieve this?

**Comment by FantasticFiasco** [comment]
I don't know. This sink usually sends log events to Logstash. When we talk about indexes we refer to the indexes in Kibana, right? If we send indexes to Logstash, are they passed on to Kibana?

**Comment by giangcoi48k** [comment]
I think I need a filter in Logstash instead of finding a way to config

**Comment by FantasticFiasco** [comment]
Please let me know if you solve the issue, and how you solved it. Thanks!
