### ISSUE TITLE
Suggestion: Update wiki to reflect what happens when buffer cannot be written

### ISSUE THREAD

**Issue by Dissimilis** [FantasticFiasco/serilog-sinks-http#37]
It can be confusing if you don't notice that sink has no write access to folder. Would be nice to add something like this to /wiki/Durable-HTTP-sink:
"If durable sink fails to write to it's buffer file, no events are sent."

**Comment by FantasticFiasco** [comment]
I can sure add that. Is something written on the Serilog selflog?

**Comment by Dissimilis** [comment]
Yes, selflog properly shows file write errors. 
But it may be more intuitive to see this behavior documented.

**Comment by FantasticFiasco** [comment]
I've created a new wiki page which basically redirects the user to Serilog, and its description of the SelfLog. You can see the page [here](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Self-help).

Thanks for creating the issue! If you find other areas of improvement, please let me know.
