### ISSUE TITLE
Configurable requestUri in HttpLogShipper

### ISSUE THREAD

**Issue by HeroXXiv** [FantasticFiasco/serilog-sinks-http#42]
What I want to implement is the configurable/changeable requestUri field, which is defined and not configurable once the application starts. Consider the case if the url is configured and syncing from database/remote config center, or different events need to be sent to different logstash forwarders.

What I am doing recently is creating my own `HttpClientWrapper` which requires a `Func<string> _urlProvider` and ignores the requestUri from the invoker, but this is not quite reasonable to define the url in the `IHttpClient` and doesn't meet the second scenario above.

Please consider provide a `Func<LogEvent, string>` uri getter in `HttpLogShipper`.

Sample of mine `HttpClientWrapper`
```
        internal class HttpRequester : IHttpClient
        {
            private readonly Func<string> _urlProvider;
            private readonly HttpClient _client;

            public HttpRequester(Func<string> urlProvider)
            {
                _urlProvider = urlProvider;
                _client = new HttpClient();
            }

            public Task<HttpResponseMessage> PostAsync(string requestUri, HttpContent content)
            {
                return _client.PostAsync(_urlProvider.Invoke(), content);
            }

            public void Dispose()
            {
                _client.Dispose();
            }
        }
```

**Comment by FantasticFiasco** [comment]
>  Consider the case if the url is configured and syncing from database/remote config center

Can you elaborate more on this use case, do you have a situation where this is the case? I can imagine that the receiver, e.g. Logstash, instances might change IPv4 address depending on how the network is configured, but one usually solve this by creating DNS records. The DNS name remains the same but its record is synced with the IP address.

> or different events need to be sent to different logstash forwarders

This use case is often solved with [Serilog filters](https://github.com/serilog/serilog/wiki/Configuration-Basics#filters). You would configure a sink to either include or exclude a particular log event, and create as many sinks as you would have receivers. Assuming you are using the durable sink, this has the added benefit of you being able to configure specific file sizes and the rotation strategies for each log event type.

**Comment by HeroXXiv** [comment]
I am building a log center service in my work, but there's some limitations and I'm not able to have a HA-LVS service right now, and I'm working with my co-workers to test the DNS TTL, but the dns server is quite old and not robust.

Another HA solution is to provide a client-side HA, just like zookeeper and memcache clients, which will receive multiple URIs when starting and check each URI's availability periodically, or define the URI out of the application, syncing and caching it. I know it is not a common case but the last thing I can do is restarting the app.

I'll check the filters for the second case, thx for the refer.
