### ISSUE TITLE
How to change naming conventions of default properties

### ISSUE THREAD

**Issue by msdotnet** [FantasticFiasco/serilog-sinks-http#46]
#### Environment

Windows Server 2012
  
#### Problem
Unable to change the default property naming conventions (eg : MessageTemplate to messageTemplate)

#### Steps to reproduce:
Pushing the info log into elastic using Http sink though elastic is resulting into PascalCase Notation for the default Serilog property.
  
#### Observed results

"events": [
  {
    "**MessageTemplate**": "Received {@activity_log}",
    "**Level**": "Information",
    "**Properties**": {
      "activityLog": {
        "dateUtc": "0001-01-01T00:00:00.0000000",
        "application": "bentleyCpv",
        "_typeTag": "ActivityLogModel",
        "eventDescription": null,
        "ipAddress": null
      }
    },
    "**Timestamp**": "2018-01-22T07:50:11.3241344-05:00"
  }
]
  
#### Expected results

"events": [
  {
    "**messageTemplate**": "Received {@activity_log}",
    "**level**": "Information",
    "**properties**": {
      "activity_log": {
        "dateUtc": "0001-01-01T00:00:00.0000000",
        "application": "bentleyCpv",
        "_typeTag": "ActivityLogModel",
        "eventDescription": null,
        "ipAddress": null
      }
    },
    "**timestamp**": "2018-01-22T07:50:11.3241344-05:00"
  }
]

**Comment by FantasticFiasco** [comment]
Unfortunately I chose to use capitalized letters in the serialized JSON in the very first version of this sink, and for that I apologize. In hindsight that was a bad decisions. I should have chosen property names that align with the guidelines of JSON.

At this point however I've come to far to change the behavior. It would be a breaking change, and would potentially upset the current users of the sink.

To your use case. Since you are using the Elastic Stack you are safe. Their indexing mechanism doesn't care about casing, you can for instance create Kibana queries all in lower case, that still would find these Serilog produced log events. But if you are really annoyed with the casing, you should copy/past one of the existing formatters and just rename the properties to your liking. Would that be a solution to your problem?

**Comment by msdotnet** [comment]
I have inherited from JsonFormatter and overridden all the methods needed and that resolves my issue.
But I see all these methods are marked Obsolete. What's the best way to do this change then ?


```
using Serilog.Events;
using Serilog.Formatting.Json;
using System;
using System.Collections.Generic;
using System.IO;

namespace Velocity.ActivityMonitoring.Api.Serilog
{
    public class CustomJsonFormatter : JsonFormatter
    {
        const string ExtensionPointObsoletionMessage = "Extension of JsonFormatter by subclassing is obsolete and will " +
                                               "be removed in a future Serilog version. Write a custom formatter " +
                                               "based on JsonValueFormatter instead. See https://github.com/serilog/serilog/pull/819.";

        /// <summary>
        /// Construct a <see cref="JsonFormatter"/>.
        /// </summary>
        /// <param name="closingDelimiter">A string that will be written after each log event is formatted.
        /// If null, <see cref="Environment.NewLine"/> will be used.</param>
        /// <param name="renderMessage">If true, the message will be rendered and written to the output as a
        /// property named RenderedMessage.</param>
        /// <param name="formatProvider">Supplies culture-specific formatting information, or null.</param>
        public CustomJsonFormatter(
            string closingDelimiter = null,
            bool renderMessage = false,
            IFormatProvider formatProvider = null)
            : base(closingDelimiter, renderMessage, formatProvider)
        {
        }


        /// <summary>
        /// Writes out the attached properties
        /// </summary>
        [Obsolete(ExtensionPointObsoletionMessage)]
        protected override void WriteProperties(IReadOnlyDictionary<string, LogEventPropertyValue> properties, TextWriter output)
        {
            output.Write(",\"{0}\":{{", "properties");
            WritePropertiesValues(properties, output);
            output.Write("}");
        }

        /// <summary>
        /// Writes out the attached exception
        /// </summary>
        [Obsolete(ExtensionPointObsoletionMessage)]
        protected override void WriteException(Exception exception, ref string delim, TextWriter output)
        {
            WriteJsonProperty("exception", exception, ref delim, output);
        }

        /// <summary>
        /// (Optionally) writes out the rendered message
        /// </summary>
        [Obsolete(ExtensionPointObsoletionMessage)]
        protected override void WriteRenderedMessage(string message, ref string delim, TextWriter output)
        {
            WriteJsonProperty("renderedMessage", message, ref delim, output);
        }

        /// <summary>
        /// Writes out the message template for the logevent.
        /// </summary>
        [Obsolete(ExtensionPointObsoletionMessage)]
        protected override void WriteMessageTemplate(string template, ref string delim, TextWriter output)
        {
            WriteJsonProperty("messageTemplate", template, ref delim, output);
        }

        /// <summary>
        /// Writes out the log level
        /// </summary>
        [Obsolete(ExtensionPointObsoletionMessage)]
        protected override void WriteLevel(LogEventLevel level, ref string delim, TextWriter output)
        {
            WriteJsonProperty("level", level, ref delim, output);
        }

        /// <summary>
        /// Writes out the log timestamp
        /// </summary>
        [Obsolete(ExtensionPointObsoletionMessage)]
        protected override void WriteTimestamp(DateTimeOffset timestamp, ref string delim, TextWriter output)
        {
            WriteJsonProperty("timestamp", timestamp, ref delim, output);
        }
    }
}
```

**Comment by FantasticFiasco** [comment]
Why don't you implement the `ITextFormatter` interface, as I've done [here](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/src/Serilog.Sinks.Http/Sinks/Http/TextFormatters/NormalTextFormatter.cs)?

**Comment by msdotnet** [comment]
I have implemented now... and all is well :-)
Thanks for all your help
