### ISSUE TITLE
How to stop event batching when using serilog-sinks-http sink

### ISSUE THREAD

**Issue by msdotnet** [FantasticFiasco/serilog-sinks-http#50]
logging performed using serilog-sinks-http are being batched into a single event. Is there any way to restrict it, so that in elastic I can have one log per document and get better Kibana support. 

**Current Log looks like this** 
`{
  "events": [
    {
      "Timestamp": "2016-11-03T00:09:11.4899425+01:00",
      "Level": "Information",
      "MessageTemplate": "Logging {@Heartbeat} from {Computer}",
      "RenderedMessage": "Logging { UserName: \"Mike\", UserDomainName: \"Home\" } from \"Workstation\"",
      "Properties": {
        "Heartbeat": {
          "UserName": "Mike",
          "UserDomainName": "Home"
        },
        "Computer": "Workstation"
      }
    },
    {
      "Timestamp": "2016-11-03T00:09:12.4905685+01:00",
      "Level": "Information",
      "MessageTemplate": "Logging {@Heartbeat} from {Computer}",
      "RenderedMessage": "Logging { UserName: \"Mike\", UserDomainName: \"Home\" } from \"Workstation\"",
      "Properties": {
        "Heartbeat": {
          "UserName": "Mike",
          "UserDomainName": "Home"
        },
        "Computer": "Workstation"
      }
    }
  ]
}`

**Expected Log: just the object not the collection**
`{
  "event": 
    {
      "Timestamp": "2016-11-03T00:09:11.4899425+01:00",
      "Level": "Information",
      "MessageTemplate": "Logging {@Heartbeat} from {Computer}",
      "RenderedMessage": "Logging { UserName: \"Mike\", UserDomainName: \"Home\" } from \"Workstation\"",
      "Properties": {
        "Heartbeat": {
          "UserName": "Mike",
          "UserDomainName": "Home"
        },
        "Computer": "Workstation"
      }
    }
}`

**Comment by FantasticFiasco** [comment]
The log events are batched for performance purposes. A single HTTP request for each and every log event is not the most efficient way to transport log events over any network.

Take a look at the wiki, there is a page dedicated to integration with the Elastic Stack. Even though this sink is a general purpose HTTP sink, the support for the Elastic Stack is excellent, and I would propose no other sinks for the job.

If you have special circumstances and the proposed route isn't for you, you can yourself modify how the batch is serialized before being sent over the network. This is done using a batch formatter. Again, this is described on the wiki as well.

**Comment by msdotnet** [comment]
Did it another way, created a Split Filter in the Logstash 
`filter {
 	split {
		field => "events"
		target => "event"
		remove_field => "events"
	}
}`
Thanks for your response.

**Comment by FantasticFiasco** [comment]
Yes, that is an alternative to configure the Logstash HTTP input plugin to use the JSON codec. Glad you got it working in the end.
