### ISSUE TITLE
Add queueLimit parameter

### ISSUE THREAD

**Issue by alexander-ivanov** [FantasticFiasco/serilog-sinks-http#51]
### Step 1: Describe your environment

* Any
  
### Step 2: Describe the problem

HttpSink is inherited from PeriodicBatchingSink but doesn't support ```queueLimit``` parameter. It would be great to have the ability to set the upper bound of the queue to know max memory consumption.

#### Observed results

* HttpSink doesn't support ```queueLimit``` parameter.
  
#### Expected results

* HttpSink supports ```queueLimit``` parameter.

**Comment by FantasticFiasco** [comment]
That sounds like a reasonable request. Would you be willing to try out a beta before I officially release this new functionality?

**Comment by alexander-ivanov** [comment]
Yes, it would be great.

**Comment by FantasticFiasco** [comment]
I'll have something for you after the weekend. Thank you for raising this issue!

**Comment by FantasticFiasco** [comment]
I've published a beta package on [NuGet](https://www.nuget.org/packages/Serilog.Sinks.Http/5.0.0-beta1-00718) with version `5.0.0-beta1-00718`, can you try it out and determine if it behaves as you'd expect when it comes to the queue limit?

**Comment by alexander-ivanov** [comment]
Yes, we will try it this week. Thank you!

**Comment by alexander-ivanov** [comment]
We've checked this fix, it works as we expected! Thank you!

**Comment by FantasticFiasco** [comment]
Thanks for verifying the functionality! I'll publish an official version of the sink tomorrow.

**Comment by FantasticFiasco** [comment]
The package is now official on nuget.org, and thank you for reporting the issue!

If you find this sink valuable, please don't hesitate to give the repository a :star:
