### ISSUE TITLE
DurableHttpSink sometimes splits log events in wrong place

### ISSUE THREAD

**Issue by mantasaudickas** [FantasticFiasco/serilog-sinks-http#54]
It looks like DurableHttpSink has some multithreading issue.
We have a netcoreapp2.0 service with quite big load and it is using DurableHttpSink for sending logs to logstash.

Sometimes it happens so that events are split in the middle somehow and logstash is unable to deserialize it as JSON.

Serilog sink is configured using configuration file as:
```
      {
        "Name": "DurableHttp",
        "Args": {
          "requestUri": "http://logstash:30000/DEV/Service",
          "bufferPathFormat": "C:/Logs/Service/Buffer-{Hour}.json"
        }
      }
```

Service is running under Windows Server behind IIS.
Sometimes we have logged events which are ending in the middle and continued in next logstash event.
For example: one event is ending like:
```
{"events": [{"Timestamp": "2018-09-10T05:01:32.9541105+02:00","Level": "Warning","MessageTemplate": "Using old values for service {serviceName}","RenderedMessage": "Using old values for service \"service\"","Properties": {"serviceName": "service","SourceContext": "ServiceMonitor","RequestId": "0HLGECVV4D9FE:00003261","RequestHeaders": {"Machine]}
```

and next event:
```
{"events": [Name": "srv01", "ThreadId": 47 }]}
```

As you can see json in both is invalid and log even is simply split into 2.
We get 2 or 3 events per day which are invalid.

For me it looks like buffer file reading before sending does not care if event is fully written. Just assuming that file reading happens at the time when writing happens, and somehow it is able to read half of even.

Using: Serilog.Sinks.Http Version=4.2.1

**Comment by mantasaudickas** [comment]
I have tried to make log producer... however was not able to reproduce that behavior on my local machine.. 
[log-producer.zip](https://github.com/FantasticFiasco/serilog-sinks-http/files/2366522/log-producer.zip)

**Comment by FantasticFiasco** [comment]
I'll try to reproduce it on my machine. At the same time I'll review the code, looking for potential problems.

Thanks for raising this issue!

**Comment by mantasaudickas** [comment]
Yes, events in buffer file looks perfectly fine.
I simply suspect that reading starts at the time when only part of event is written as reader does not do any validations for that.

**Comment by FantasticFiasco** [comment]
Just wanted to give you an update. I've been able to consistently reproduce the problem, and am now working on fixing the issue.

Thank you for your patience.

**Comment by mantasaudickas** [comment]
Nice, thank you very much for looking at this so fast!

**Comment by FantasticFiasco** [comment]
There is now a pre-release available on [nuget.org](https://www.nuget.org/packages/Serilog.Sinks.Http/5.0.1-issue-54-00770). Would you be able to try it out for a couple of days to verify that it fixes your problem?

Thanks for your help!

**Comment by mantasaudickas** [comment]
Hi, yes, we will test new package and will give you results.

**Comment by mantasaudickas** [comment]
Until now we do not get any more issues. I guess we could release it now :)

**Comment by FantasticFiasco** [comment]
Very good! I'll release an official fix tonight.

Thank you for reporting this issue.

**Comment by FantasticFiasco** [comment]
The release is currently being validated on NuGet, it should be available within the hour.
