### ISSUE TITLE
Custom Formatting

### ISSUE THREAD

**Issue by ismail-tellioglu** [FantasticFiasco/serilog-sinks-http#59]
I am using Serilog HTTP (50.1 version) sink for logging to Logstash in my .Net Core Project. In startup.cs I have following code to enable serilog. 

` Log.Logger = new LoggerConfiguration()
        .Enrich.FromLogContext()
        .WriteTo.Http("http://mylogstashhost.com:5000").Enrich.WithProperty("user", "xxx").Enrich.WithProperty("serviceName", "yyy")
        .MinimumLevel.Warning()
        .CreateLogger();`
  
My events are being send as the following format.

`{"events":[{"Timestamp":"2018-10-19T18:16:27.6561159+01:00","Level":"Warning","MessageTemplate":"abc","RenderedMessage":"abc","user":"xxx","serviceName":"yyy","Properties":{"ActionId":"b313b8ed-0baf-4d75-a6e2-f0dbcb941f67","ActionName":"MyProject.Controllers.HomeController.Index","RequestId":"0HLHLQMV1EBCJ:00000003","RequestPath":"/"}}]}`

But seems receiving Logstash endpoint does not accept such format and I can not see my logs on Kibana. But when I send as following format all is ok.

`{"Timestamp":"2018-10-19T18:16:27.6561159+01:00","Level":"Warning","MessageTemplate":"abc","RenderedMessage":"abc","user":"xxx","serviceName":"yyy","Properties":{"ActionId":"b313b8ed-0baf-4d75-a6e2-f0dbcb941f67","ActionName":"MyProject.Controllers.HomeController.Index" ,"RequestId":"0HLHLQMV1EBCJ:00000003","RequestPath":"/"}}`

So Logstash doesnt like the event to be in Events{} and also it wants "user" and "ServiceName" tags out of "Properties". I read posts about custom formatting, tried to use CompactJsonFormatter, JsonFormatter but none of them gave me what i wanted. Is there a way to achieve this ?

**Comment by FantasticFiasco** [comment]
I think you should start with the Elastic sample application listed in README.md, it configures the sink to work with Logstash. If you still need a custom event formatter you should take a look at the wiki, it has more information on the subject.

**Comment by FantasticFiasco** [comment]
My best guess is that Logstash hasn't enabled the HTTP input plugin, and if you wish to send log events over HTTP you need to configure this on the receiving side.

Regarding custom event formats you can read the [wiki](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Event-formatters) where it describes custom formatters. Basically it boils down to you implementing a interface, of which you can find several examples in the source of this repo.

**Comment by ismail-tellioglu** [comment]
Http input plugin is enabled. As I mentioned if I send the json as following format (by using postman or curl), I can see logs.  Maybe the receiving side made these two params(user, serviceName) required.

`[{"Timestamp":"2018-10-20T19:12:57.4797898+01:00","Level":"Warning","MessageTemplate":"abc","RenderedMessage":"abc","Properties":{"ActionId":"d73ddb7a-c610-4f30-8b07-e0880f4e1d20","ActionName":"MyProject.Controllers.HomeController.Index","RequestId":"0HLHMKRHNJPBN:00000001","RequestPath":"/"},"user":"xxx","serviceName":"yyy"}] `

Ok I will try to find some way from wiki page and if I can I will share the solution.

**Comment by FantasticFiasco** [comment]
You should also be inspired by the [default event formatter](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/src/Serilog.Sinks.Http/Sinks/Http/TextFormatters/NormalTextFormatter.cs). With minimal changes you ought to get the format you want.

**Comment by ismail-tellioglu** [comment]
Thanks for your help. I could achieve the format i need by modifying  a little [ArrayBatchFormatter](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/src/Serilog.Sinks.Http/Sinks/Http/BatchFormatters/ArrayBatchFormatter.cs)

`using Serilog.Debugging;
using Serilog.Events;
using Serilog.Formatting;
using Serilog.Formatting.Json;
using Serilog.Parsing;
using Serilog.Sinks.Http.BatchFormatters;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ACOACH
{
    public class MyFormat : BatchFormatter
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArrayBatchFormatter"/> class.
        /// </summary>
        /// <param name="eventBodyLimitBytes">
        /// The maximum size, in bytes, that the JSON representation of an event may take before it
        /// is dropped rather than being sent to the server. Specify null for no limit. Default
        /// value is 256 KB.
        /// </param>
        public MyFormat(long? eventBodyLimitBytes = 256 * 1024)
            : base(eventBodyLimitBytes)
        {
        }

        /// <summary>
        /// Format the log events into a payload.
        /// </summary>
        /// <param name="logEvents">
        /// The events to format.
        /// </param>
        /// <param name="output">
        /// The payload to send over the network.
        /// </param>
        public override void Format(IEnumerable<string> logEvents, TextWriter output)
        {
            if (logEvents == null) throw new ArgumentNullException(nameof(logEvents));
            if (output == null) throw new ArgumentNullException(nameof(output));

            // Abort if sequence of log events is empty
            if (!logEvents.Any())
            {
                return;
            }

            output.Write("[");

            var delimStart = string.Empty;

            foreach (var logEvent in logEvents)
            {
                if (string.IsNullOrWhiteSpace(logEvent))
                {
                    continue;
                }
                **string adjustedString = "{\"user\":\"xxx\",\"serviceName\" : \"yyy\"," + logEvent.Substring(1);**
                if (CheckEventBodySize(adjustedString))
                {
                    output.Write(delimStart);
                    output.Write(adjustedString);
                    delimStart = ",";
                }
            }

            output.Write("]");
        }
    }
}
`

**Comment by FantasticFiasco** [comment]
Very good, let me know if you encounter any other problems.
