### ISSUE TITLE
Any chance you could upgrade you could upgrade rolling files, and provide new sink for it

### ISSUE THREAD

**Issue by sachabarber** [FantasticFiasco/serilog-sinks-http#67]
So I have just spent quite a bit of time messing about with what I thought would be working just fine. But there seems to be an issue with the package you depend on for the durable files. So right now you depend on this package

**Serilog.Sinks.RollingFile" Version="3.*" **

https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/src/Serilog.Sinks.Http/Serilog.Sinks.Http.csproj#L28

But there is a lot of chat about this not rolling the files correctly at its own GitHub page : https://github.com/serilog/serilog-sinks-rollingfile/issues/26

![image](https://user-images.githubusercontent.com/1457596/48554767-359e9c80-e8d7-11e8-9c4e-1b69712ed2b7.png)

This seems to have been fixed in v 4.0.0.0 of a different (newer) sink , which is available on NuGet

https://www.nuget.org/packages/serilog.sinks.file/

Which is what the RollingFile page is recommending people use now anyway

![image](https://user-images.githubusercontent.com/1457596/48555081-0ccad700-e8d8-11e8-9649-ebf9d465b565.png)

Just wondering if you could push out a new version of your sink which could potentially add another sink that could work with this newer recommended **serilog.sinks.file** (actually working rolling files based on size)

I would see this as 1 new Sink extension method say something like *DurableHttpUsingSeriLogSizeRolled* (or whatever you like) this would then use a BRAND new sink, which would internally use the newer recommended **serilog.sinks.file** 

Basically you can not rely on this sink doing the right thing right now, due to the dependency it has on OLD Serilog.Sinks.RollingFile, which doesn't roll properly.

The trick will be to make sure you take all the parameters required to create this sink

```
/// <summary>
/// Write log events to the specified file.
/// </summary>
/// <param name="path">Path to the file.</param>
/// <param name="formatter">A formatter, such as <see cref="JsonFormatter"/>, to convert the log events into
/// text for the file. If control of regular text formatting is required, use the other
/// overload of <see cref="File(LoggerSinkConfiguration, string, LogEventLevel, string, IFormatProvider, long?, LoggingLevelSwitch, bool, bool, TimeSpan?, RollingInterval, bool, int?, Encoding)"/>
/// and specify the outputTemplate parameter instead.
/// </param>
/// <param name="fileSizeLimitBytes">The approximate maximum size, in bytes, to which a log file will be allowed to grow.
/// For unrestricted growth, pass null. The default is 1 GB. To avoid writing partial events, the last event within the limit
/// will be written in full even if it exceeds the limit.</param>
/// <param name="buffered">Indicates if flushing to the output file can be buffered or not. The default
/// is false.</param>
/// <param name="retainedFileCountLimit">The maximum number of log files that will be retained,
/// including the current log file. For unlimited retention, pass null. The default is 31.</param>
/// <param name="encoding">Character encoding used to write the text file. The default is UTF-8 without BOM.</param>
/// <param name="buffered">Indicates if flushing to the output file can be buffered or not. The default
/// is false.</param>
/// <param name="shared">Allow the log file to be shared by multiple processes. The default is false.</param>
/// <param name="rollingInterval">The interval at which logging will roll over to a new file.</param>
/// <param name="rollOnFileSizeLimit">If <code>true</code>, a new file will be created when the file size limit is reached. Filenames 
/// will have a number appended in the format <code>_NNN</code>, with the first filename given no number.</param>


new RollingFileSink(path, formatter, fileSizeLimitBytes, retainedFileCountLimit, encoding, buffered, shared, rollingInterval, rollOnFileSizeLimit);
```

**Comment by FantasticFiasco** [comment]
I'll definitelly look into this tonight, and assuming no suprises, it should be a easy feature addition.

**Comment by sachabarber** [comment]
That would be amazing, I think the code should be fairly close to what you have already just 1 new sink/confiuration extension method

**Comment by sachabarber** [comment]
This 1 setting is an absolute MUST though, you MUST provide this in your exposed properties `rollOnFileSizeLimit`. Thats the crucial one. I think if you follow properties outlined above everyone should be able to work with that

**Comment by sachabarber** [comment]
For my money I think a new Configuration extension method would be best, along with brand new Sink. That way you wont break any existing stuff

**Comment by sachabarber** [comment]
No problem. We still need this improvement for another area, so when its ready let me know

**Comment by sachabarber** [comment]
Im so sorry that I did not get around to this, but this may come back on our Radar very soon. We just had bigger issues to attend to. I will likely try this soon

**Comment by FantasticFiasco** [comment]
No worries!

These changes aren't blocking anything else. When I feel confident that your requirements are met, I'll prepare the merge.

**Comment by sachabarber** [comment]
So I finally got round to trying this. And it looks good. Could you let me know when you an merge and publish for real

**Comment by FantasticFiasco** [comment]
Thanks for verifying the changes! My hopes are to get this sorted out this week. I'll get back to you.

**Comment by FantasticFiasco** [comment]
Version 5.2.0 is now available on nuget.org. If you experience anything unexpected, please let me know.

Have a nice weekend!
