### ISSUE TITLE
'Timestamp' field does not display UTC time correctly

### ISSUE THREAD

**Issue by gilzig** [FantasticFiasco/serilog-sinks-http#70]
**Describe the bug**
When I use this sink, and examine the json object returned by Kibana, I see that the Timestamp field does not include correct timezone information. 
For example, the current value is:
     "Timestamp": "2019-02-26T08:00:07.0552471+00:00", 
However, I am in time zone UTC+2, so I would expect the value to be:
     "Timestamp": "2019-02-26T08:00:07.0552471+**02:00**", 
**To Reproduce**
Just examine the Timestamp value and check if the time is incorrect

**Expected behavior**
Timestamp should contain correct UTC time. 
This is very important when I have a few services with different timezone writing to the same log. If I want to sort by the Timestamp - I get incorrect order.

Any way around this limitation?

Thanks,
Gil

**Comment by gilzig** [comment]
My bad - this was caused because when my code runs within docker-compose, the utc time zone is changed to +0...
When the code runs externally it is OK.
I am closing this since its not a bug.

**Comment by FantasticFiasco** [comment]
These kind of issues are the best! Thanks for figuring it out yourself.

If you find anything odd, please don't hesitate to open a new issue.

Have a nice day!
