### ISSUE TITLE
Headers for (Durable)Http sinks

### ISSUE THREAD

**Issue by qodex2** [FantasticFiasco/serilog-sinks-http#71]
**Is your feature request related to a problem? Please describe.**
I can't find a way to add headers to a (Durable)Http sink.  Is there a way and I've just missed it?  I need to add an Authorization header.

**Describe the solution you'd like**
It sounds like this might be a similar type of issue: https://github.com/serilog/serilog-sinks-elasticsearch/issues/87.  Better for me would be another ctor parameter like "headers" that accepts a delimited list of headers and values.  Even simpler, an "authorization" parameter that accepts a string.

**Describe alternatives you've considered**
Use a custom HttpClient?

**Comment by FantasticFiasco** [comment]
Hi and welcome to the project!

Yes, I would propose to implement your own `IHttpClient` and configure it with a default header, or if the header value change over time, set it for each request.

`IHttpClient` only contains one method, and the API conforms with `HttpClient`, thus it should be a walk in the park to create your own. The default HTTP client used by the sink looks like [this](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/src/Serilog.Sinks.Http/Sinks/Http/Private/Network/DefaultHttpClient.cs). You can use it for inspiration if you like :-)

Please tell me if you run into any problems.

**Comment by FantasticFiasco** [comment]
I've added a [chapter](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Custom-HTTP-client) in the wiki describing custom HTTP clients. Please let me know if the information provided is sufficient or needs improving, Don't forget to give the project a star if you find it useful :-)

**Comment by qodex2** [comment]
That solves my problem.  Thanks!
