### ISSUE TITLE
Is it possible to set (batch) formatter in configuration file?

### ISSUE THREAD

**Issue by alesdvorakcz** [FantasticFiasco/serilog-sinks-http#80]
Hello I tried to set batch Formatter in config file but I get exception
`'Invalid cast from 'System.String' to 'Serilog.Sinks.Http.IBatchFormatter'`

My configuration file looks like this:
```
{
    "Name": "DurableHttpUsingFileSizeRolledBuffers",
    "Args": {
        "requestUri": "http://localhost:31311",
        "batchFormatter": "ArrayBatchFormatter"
    }
}
```

Is there any way how to do this or is the only way to configure logger in code?

Thanks

**Comment by FantasticFiasco** [comment]
Hi alesdvorakcz!

It is definitely possible, but you have to specify the full name of the class. Here is [an example from the tests](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/test/Serilog.Sinks.HttpTests/appsettings_http.json#L13).

I think I will have to add some examples in the documentation. Thanks for bringing it to my attention.

**Comment by alesdvorakcz** [comment]
Thanks for super quick answer!

Adding this to documentation would be nice.

**Comment by FantasticFiasco** [comment]
Could I give you a ping when it's done, for you to verify that the added documentation is informative enough? Do you have any wishes where you would like to read this kind of documentation, README or wiki?

**Comment by alesdvorakcz** [comment]
I was searching for it in wiki so I guess its where other users would search for it :) but its up to you where you will put it. 
This sink/documentation is not that complex so I think it won't be hard to find it anywhere...

**Comment by alesdvorakcz** [comment]
One more suggestion is period format in configuration file. I expected I should set it as seconds(integer) but its actually timespan so if I want 5 I have to set it as "00:00:05"

**Comment by FantasticFiasco** [comment]
I've added [the following page](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Application-settings) to the wiki. Do you think the information there is sufficient?

**Comment by alesdvorakcz** [comment]
Its perfect! Thank you once again for your amazing work.

**Comment by FantasticFiasco** [comment]
If you find the sink useful, and already haven't, don't forget to give the repository a star.

Best of luck in all your future development endeavors!
