### ISSUE TITLE
Add fluentd support

### ISSUE THREAD

**Issue by Pzixel** [FantasticFiasco/serilog-sinks-http#83]
**Is your feature request related to a problem? Please describe.**
At this moment it's not possible to write logs into Fluentd. It's possible to enable `http` plugin there but it accept data in different format

**Describe the solution you'd like**
I'd like to be able to write
```cs
ILogger log = new LoggerConfiguration()
  .MinimumLevel.Verbose()
  .WriteTo.Http(new FluentdSink("http://my.fluent.d:9880"))
  .CreateLogger();
```

and write event there.

**Describe alternatives you've considered**
Existing [Fluentd sink package](https://github.com/VQComms/Serilog.Sinks.Fluentd.Core) is unusable and buggied. The most urgent concern is it escapes everything with quotes, so I'm unable to execute range and others non-text queries.

**Additional context**

Here is a link to fluentd http format documentation: https://docs.fluentd.org/input/http#basic-usage

**Comment by FantasticFiasco** [comment]
Hi!

Is seems it would be possible to create custom event and batch formatters that would create a payload conforming to fluentd. Have you tried creating your own formatters? The wiki has extensive information on the topics but please let me know it you find them lacking..

**Comment by Pzixel** [comment]
Sounds interesting. I'l look at it later. Thanks for response.

**Comment by FantasticFiasco** [comment]
If you provide me with your fluentd setup and describe to me how to start the service locally I can see if I can help you out.

**Comment by Pzixel** [comment]
Of course:

```yml
<source>
  @type http
  port 9880
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
</source>
<match myapp.**>
  @type copy
  <store>
    @type elasticsearch
    logstash_format true
    hosts prod-es-logs1:9200,prod-es-logs2:9200,prod-es-logs3:9200,prod-es-logs4:9200,prod-es-logs5:9200
    index_name log-%Y%m%d
    type_name myapp-web
    include_tag_key true
  </store>
  <buffer>
    @file path /var/fluentd/buffer/myapp
    total_limit_size 1024MB
    chunk_limit_size 16MB
    flush_mode interval
    flush_interval 5s
    flush_thread_count 8
    retry_type exponential_backoff
    retry_timeout 1h
    retry_max_interval 30
    overflow_action drop_oldest_chunk
  </buffer>
</match>
```

**Comment by FantasticFiasco** [comment]
The Fluentd http input plugin in  is supporting [JSON arrays of log events](https://docs.fluentd.org/input/http#handle-large-data-with-batch-mode), and since this sink [supports that as well](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Batch-formatters#batch-formatter-2---arraybatchformatter) I'm confident we can make it work.

I am about to create a repository showcasing the integration, and my hypothesis is that writing like this _should just work_:

```csharp
ILogger log = new LoggerConfiguration()
  .MinimumLevel.Verbose()
  .WriteTo.Http("http://my.fluent.d:9880/myapp.test", batchFormatter: new ArrayBatchFormatter())
  .CreateLogger();
```

**Comment by FantasticFiasco** [comment]
I've created a [new sample repository](https://github.com/FantasticFiasco/serilog-sinks-http-sample-fluentd) showcasing this sink sending log events to Fluentd. I'll close this issue, but if you find any other issues please don't hesitate to create them.
