### ISSUE TITLE
never sends HTTP request

### ISSUE THREAD

**Issue by mikeblas** [FantasticFiasco/serilog-sinks-http#92]
I'm unable to get this sink to send anything to my Logstash server.

I'm using this code in a Net Core 3.1 console application:

```
            Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));

            var log = new LoggerConfiguration()
             .WriteTo.Console()
             .WriteTo.Http("http://ularge1:8080")
             .CreateLogger();

            log.Information("Testing");
```

The testing message appears in the console, but the log entry is never sent to my server. I'm able to send something with curl and have no problem.

What debugging mechanisms are available?

**Comment by FantasticFiasco** [comment]
Hi mikeblas!

When it comes to console applications, the most probable issue is that you've forgotten to flush the log events, thus the application is terminated before the log events are sent over the network. Please note that writing log events is an asynchronous operation, it's not synchronous.

Lets try to flush the log events before terminating the application, see [Lifecycle of Loggers](https://github.com/serilog/serilog/wiki/Lifecycle-of-Loggers#in-all-apps) for more information.

If this doesn't work it probably is network related, but lets diagnose that when we've ruled out the most probable issue.

**Comment by FantasticFiasco** [comment]
Closed due to inactivity
